import N5R2.Check
/-! N = 5, Riesz s = 2: the three-point bound `17/4 ≤ ∑_{i<j} H(⟪x i, x j⟫)` for five unit vectors of `ℝ³`,
from the checked facially reduced certificate `cf` and `ThomsonN7.Cert.Cert3.soundN`.  `Hn` is `H` written out
in the monomial basis (`Hn_eq`).  The comparison `H ≤ φ₂` is not part of this module.

Generated by `lean/gen/emit_n5.py` from `cert_n5_s2_short.json`
(sha256 b347cfbf8dc0450ad3ae95a38308f068d33f074ad96d84ce3251bdadefd20a09).  Do not edit; regenerate. -/

open Real

namespace N5R2
open ThomsonN7 ThomsonN7.Cert ThomsonN7.Cert.Cert3

open scoped RealInnerProductSpace

/-- The degree-10 minorant `H` of the certificate, in the monomial basis (exact rationals). -/
noncomputable def Hn (x : ℝ) : ℝ :=
    (1 / 2 : ℝ) +
    (1 / 2 : ℝ) * x +
    (10279028337839033858341133629 / 25705722895745954321793024000 : ℝ) * x ^ 2 +
    (-1084244369104437683349886391 / 171371485971639695478620160000 : ℝ) * x ^ 3 +
    (-150749397997864698924804973603 / 514114457914919086435860480000 : ℝ) * x ^ 4 +
    (13467492503835436663199671991 / 85685742985819847739310080000 : ℝ) * x ^ 5 +
    (43210707187387183998680214971 / 128528614478729771608965120000 : ℝ) * x ^ 6 +
    (-2916104247463196871929724113 / 21421435746454961934827520000 : ℝ) * x ^ 7 +
    (600681775 / 8589934592 : ℝ) * x ^ 8 +
    (1834674173541375428092543 / 3347099335383587802316800 : ℝ) * x ^ 9 +
    (322207483 / 1073741824 : ℝ) * x ^ 10

/-- `Hn` is the minorant `cf.Hf` of the checked certificate. -/
theorem Hn_eq (x : ℝ) : Hn x = cf.Hf x := by
  have g0 : h_.getD 0 0 = (6169373494979029037230325760000 : Int) := rfl
  have g1 : h_.getD 1 0 = (6169373494979029037230325760000 : Int) := rfl
  have g2 : h_.getD 2 0 = (4933933602162736252003744141920 : Int) := rfl
  have g3 : h_.getD 3 0 = (-78065594575519513201191820152 : Int) := rfl
  have g4 : h_.getD 4 0 = (-3617985551948752774195319366472 : Int) := rfl
  have g5 : h_.getD 5 0 = (1939318920552302879500752766704 : Int) := rfl
  have g6 : h_.getD 6 0 = (4148227889989169663873300637216 : Int) := rfl
  have g7 : h_.getD 7 0 = (-1679676046538801398231521089088 : Int) := rfl
  have g8 : h_.getD 8 0 = (862830835767545911916544000000 : Int) := rfl
  have g9 : h_.getD 9 0 = (6763342873342926378120350515200 : Int) := rfl
  have g10 : h_.getD 10 0 = (3702600124299723811205283840000 : Int) := rfl
  have e : cf.Hf x = (∑ j ∈ Finset.range 11, ((h_.getD j 0 : ℤ) : ℝ) * x ^ j) / ((lam_ : ℕ) : ℝ) := rfl
  rw [e]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10]
  unfold Hn lam_
  push_cast
  ring

theorem lam_pos : 0 < cf.Lam := by decide +kernel

theorem eps_div : (cf.eps : ℝ) / (cf.Lam : ℝ) = 17 / 4 := by
  have h1 : cf.eps = (52439674707321746816457768960000 : Int) := rfl
  have h2 : cf.Lam = 12338746989958058074460651520000 := rfl
  rw [h1, h2]
  norm_num

theorem cut : ((cf.an : ℤ) : ℝ) / ((cf.ad : ℕ) : ℝ) ≤ -1 := by
  have h1 : cf.an = -1 := rfl
  have h2 : cf.ad = 1 := rfl
  rw [h1, h2]
  norm_num

/-- **The three-point bound for `N = 5`.**  For all unit vectors `x 0, …, x 4` of `ℝ³`,
`17/4 ≤ ∑_{i<j} Hn ⟪x i, x j⟫`. -/
theorem bound (x : Fin 5 → R3) (hx : ∀ i, ‖x i‖ = 1) :
    (17 / 4 : ℝ) ≤ ∑ i, ∑ j ∈ Finset.Ioi i, Hn ⟪x i, x j⟫ := by
  have h := Cert3.soundN cf [nF0, nF1, nF2, nF3] [nS0, nS1, nS2, nS3, nS4, nS5, nS6, nS7]
    cf_hF cf_hS (by decide +kernel) lam_pos (by decide +kernel) cf_chk cut x hx
  rw [eps_div] at h
  simp only [Hn_eq]
  exact h

end N5R2
