import ThomsonGen.Case1Stat
import N5R2.ChkF
import N5R2.ChkS0
import N5R2.ChkS1
import N5R2.ChkS2
import N5R2.ChkS3
import N5R2.ChkS4
import N5R2.ChkS5
import N5R2.ChkS6
import N5R2.ChkS7
import N5R2.ChkN0
import N5R2.ChkN1
import N5R2.ChkN2
import N5R2.ChkN3
import N5R2.ChkN4
import N5R2.ChkN5
import N5R2.ChkN6
import N5R2.ChkN7
/-! N = 5, s = 2: assembly of the chunked checks.  `chk cf.idE = true` (ℓ¹ < 2^120, degrees < 11, Kronecker value 0;
soundness: `Kron.Ex.ev_eq_zero_of_kev`), and the block facts `List.Forall₂ Cert3.FOK cf.F _`, `List.Forall₂ Cert3.SOK cf.S _`
(the composition mirrors upstream `Case1.lean`; the piece statistics are named constants so that the big literals
stay out of the elaborated terms).

Attribution: adapted from huwngtran/thomson-n7-lean @ 25f2fa5, `ThomsonN7/Solution.lean` (ours ← upstream): `cf_chk` ← `Case1.cf_chk`.

Generated by `lean/gen/emit_n5.py` from `cert_n5_s2_short.json`
(sha256 b347cfbf8dc0450ad3ae95a38308f068d33f074ad96d84ce3251bdadefd20a09).  Do not edit; regenerate. -/

namespace N5R2
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.Cert.Cert3

-- large literals: elaboration budget only (no effect on what is checked)
set_option maxHeartbeats 0

theorem cf_K : cf.K = 4 := rfl

theorem cf_S : cf.S = [S0, S1, S2, S3, S4, S5, S6, S7] := rfl

theorem range_K : List.range 4 = [0, 1, 2, 3] := rfl

/-- The statistics of the whole identity expression: `ℓ¹`-norm below `2 ^ 120`, degrees `10, 10, 10`, Kronecker value `0`. -/
theorem idE_stat : ThomsonN7.Case1.c1Stat 120 11 cf.idE = (1296135083685572005849667712854206560, 10, 10, 10, (0 : Int)) := by
  rw [ThomsonN7.Case1.c1Stat_idE, cf_K, cf_S, range_K]
  simp only [List.map_cons, List.map_nil]
  rw [stat_H, stat_F0, stat_F1, stat_F2, stat_F3, stat_S0, stat_S1, stat_S2, stat_S3, stat_S4, stat_S5, stat_S6, stat_S7]
  decide +kernel

/-- The Kronecker check of the identity expression. -/
theorem cf_chk : chk cf.idE = true := by
  have h := ThomsonN7.Case1.c1Stat_eq 120 11 cf.idE
  rw [idE_stat] at h
  simp only [Prod.mk.injEq] at h
  obtain ⟨hl, hx, hy, hz, hk⟩ := h
  unfold chk
  rw [← hl, ← hx, ← hy, ← hz]
  have hW : Nat.log2 1296135083685572005849667712854206560 + 1 = 120 := by decide +kernel
  have hD : max 10 (max 10 10) + 1 = 11 := by decide +kernel
  rw [hW, hD]
  exact decide_eq_true hk.symm

/-- The kernel blocks are the expansions of the checked witnesses. -/
theorem cf_hF : List.Forall₂ Cert3.FOK cf.F [nF0, nF1, nF2, nF3] :=
  .cons F0_fok (.cons F1_fok (.cons F2_fok (.cons F3_fok (.nil))))

/-- The SOS blocks are the expansions of the checked witnesses. -/
theorem cf_hS : List.Forall₂ Cert3.SOK cf.S [nS0, nS1, nS2, nS3, nS4, nS5, nS6, nS7] :=
  .cons S0_sok (.cons S1_sok (.cons S2_sok (.cons S3_sok (.cons S4_sok (.cons S5_sok (.cons S6_sok (.cons S7_sok (.nil))))))))

end N5R2
