import N5R1.Check
import N5R1.Corner
/-! N = 5, Coulomb (s = 1): the three-point bound `1/2 + 3√2 + √3 ≤ ∑_{i<j} Hn(⟪x i, x j⟫)` for five unit vectors of `ℝ³`,
from the checked component certificates `cf0, cf1, cf2` (identities), the checked `K`-blocks with corner witnesses
(positivity at `(1, √2, √3)` through the box, `w_aff`) and `ThomsonN7.Cert.Cert3K.soundK`.  `Hn = Hn0 + √2·Hn1 + √3·Hn2` in the
monomial basis.  The comparison `Hn ≤ φ₁` is not part of this module.

Generated by `lean/gen/emit_n5_s1.py` from `cert_n5_s1_short.json`
(sha256 66c5baa88a130761295e1a161f9fe35f8218c28e3defddc67ad22bcd5361e2e0).  Do not edit; regenerate. -/

open Real

namespace N5R1
open ThomsonN7 ThomsonN7.Cert ThomsonN7.Cert.Cert3 ThomsonN7.Cert.KB

open scoped RealInnerProductSpace

/-- The weights `1, √2, √3` of the components. -/
noncomputable def w : ℕ → ℝ := fun c => [1, √2, √3].getD c 0

/-- The kernel block sizes. -/
def mF : ℕ → ℕ := fun k => [6, 5, 4, 3].getD k 0

def gs : ℕ → List ℕ := fun i => (cf0.S.getD i Cert3K.sDflt).g
def σs : ℕ → ℕ := fun i => (cf0.S.getD i Cert3K.sDflt).σ
def zs : ℕ → List (ℕ × ℕ × ℕ) := fun i => (cf0.S.getD i Cert3K.sDflt).z

theorem lo2 : ((6074000999 : ℝ) / 4294967296) ≤ √2 := by
  rw [show ((6074000999 : ℝ) / 4294967296) = √(((6074000999 : ℝ) / 4294967296) ^ 2) from (Real.sqrt_sq (by norm_num)).symm]
  exact Real.sqrt_le_sqrt (by norm_num)

theorem hi2 : √2 ≤ ((6074001000 : ℝ) / 4294967296) := by
  rw [show ((6074001000 : ℝ) / 4294967296) = √(((6074001000 : ℝ) / 4294967296) ^ 2) from (Real.sqrt_sq (by norm_num)).symm]
  exact Real.sqrt_le_sqrt (by norm_num)

theorem lo3 : ((7439101573 : ℝ) / 4294967296) ≤ √3 := by
  rw [show ((7439101573 : ℝ) / 4294967296) = √(((7439101573 : ℝ) / 4294967296) ^ 2) from (Real.sqrt_sq (by norm_num)).symm]
  exact Real.sqrt_le_sqrt (by norm_num)

theorem hi3 : √3 ≤ ((7439101574 : ℝ) / 4294967296) := by
  rw [show ((7439101574 : ℝ) / 4294967296) = √(((7439101574 : ℝ) / 4294967296) ^ 2) from (Real.sqrt_sq (by norm_num)).symm]
  exact Real.sqrt_le_sqrt (by norm_num)

/-- A linear functional nonnegative at the four (scaled) corners of the box is nonnegative at `(1, √2, √3)`
(`N5R1.affine_nonneg_of_corners`, with the third coordinate unused). -/
theorem w_aff : AffOK 3 w κs := by
  intro Q hQ
  have hD : (0 : ℝ) < 4294967296 := by norm_num
  have hk : ∀ κ ∈ κs, 0 ≤ (κ.getD 0 0 : ℝ) * Q 0 + (κ.getD 1 0 : ℝ) * Q 1 + (κ.getD 2 0 : ℝ) * Q 2 := by
    intro κ hκ
    have := hQ κ hκ
    simpa [Finset.sum_range_succ] using this
  have h00 := hk κ0 (by simp [κs])
  have h01 := hk κ1 (by simp [κs])
  have h10 := hk κ2 (by simp [κs])
  have h11 := hk κ3 (by simp [κs])
  simp only [κ0, κ1, κ2, κ3, List.getD_cons_zero, List.getD_cons_succ] at h00 h01 h10 h11
  push_cast at h00 h01 h10 h11
  have key := N5R1.affine_nonneg_of_corners (Q 0) ![Q 1, Q 2, 0] ![6074000999 / 4294967296, 7439101573 / 4294967296, 0]
    ![6074001000 / 4294967296, 7439101574 / 4294967296, 0] ![√2, √3, 0]
    (by intro i; fin_cases i <;> simp [lo2, lo3])
    (by intro i; fin_cases i <;> simp [hi2, hi3])
    (by
      intro b
      simp only [N5R1.aff, N5R1.corner, Fin.sum_univ_three]
      simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two, Matrix.head_cons,
        Matrix.tail_cons, zero_mul, add_zero, ite_self]
      cases b 0 <;> cases b 1 <;> simp only [Bool.false_eq_true, ite_true, ite_false]
      · have := div_nonneg h00 hD.le
        convert this using 1; field_simp; ring
      · have := div_nonneg h01 hD.le
        convert this using 1; field_simp; ring
      · have := div_nonneg h10 hD.le
        convert this using 1; field_simp; ring
      · have := div_nonneg h11 hD.le
        convert this using 1; field_simp; ring)
  simp only [N5R1.aff, Fin.sum_univ_three, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two,
    Matrix.head_cons, Matrix.tail_cons, zero_mul, add_zero] at key
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, w, List.getD_cons_zero, List.getD_cons_succ]
  linarith

/-- The `1`-component of the minorant, in the monomial basis (exact rationals). -/
noncomputable def Hn0 (x : ℝ) : ℝ :=
    (0 : ℝ) +
    (0 : ℝ) * x +
    (4520899263300623297727283069 / 1269418414604738485026816000 : ℝ) * x ^ 2 +
    (39621715652884843138673766737 / 4231394715349128283422720000 : ℝ) * x ^ 3 +
    (-135984712038468721580456146529 / 12694184146047384850268160000 : ℝ) * x ^ 4 +
    (-67729399165224629689927639937 / 2115697357674564141711360000 : ℝ) * x ^ 5 +
    (52366784668438822307967964453 / 3173546036511846212567040000 : ℝ) * x ^ 6 +
    (19908240956088577288193322791 / 528924339418641035427840000 : ℝ) * x ^ 7 +
    (-49405960589 / 4294967296 : ℝ) * x ^ 8 +
    (-17838698377100911771418761 / 1322310848546602588569600 : ℝ) * x ^ 9 +
    (4458891987 / 1073741824 : ℝ) * x ^ 10

theorem Hn0_eq (x : ℝ) : Hn0 x = cf0.Hf x := by
  have g0 : h0_.getD 0 0 = (0 : Int) := rfl
  have g1 : h0_.getD 1 0 = (0 : Int) := rfl
  have g2 : h0_.getD 2 0 = (87886281678564116907818382861360 : Int) := rfl
  have g3 : h0_.getD 3 0 = (231073845687624405184745407610184 : Int) := rfl
  have g4 : h0_.getD 4 0 = (-264354280202783194752406748852376 : Int) := rfl
  have g5 : h0_.getD 5 0 = (-789995711863180080703315992225168 : Int) := rfl
  have g6 : h0_.getD 6 0 = (407204117581780282266758891586528 : Int) := rfl
  have g7 : h0_.getD 7 0 = (928838890047268661957947668136896 : Int) := rfl
  have g8 : h0_.getD 8 0 = (-283870681889127099881775759360000 : Int) := rfl
  have g9 : h0_.getD 9 0 = (-332912924592808055842925485286400 : Int) := rfl
  have g10 : h0_.getD 10 0 = (102477409100428884130517483520000 : Int) := rfl
  have e : cf0.Hf x = (∑ j ∈ Finset.range 11, ((h0_.getD j 0 : ℤ) : ℝ) * x ^ j) / ((lam_ : ℕ) : ℝ) := rfl
  rw [e]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10]
  unfold Hn0 lam_
  push_cast
  ring

/-- The `√2`-component of the minorant, in the monomial basis (exact rationals). -/
noncomputable def Hn1 (x : ℝ) : ℝ :=
    (1 / 2 : ℝ) +
    (1 / 4 : ℝ) * x +
    (-5180363913766531620960138173 / 1142476573144264636524134400 : ℝ) * x ^ 2 +
    (-12726968268388251303854438483 / 7616510487628430910160896000 : ℝ) * x ^ 3 +
    (308005312564408054397721196361 / 22849531462885292730482688000 : ℝ) * x ^ 4 +
    (12784008643860474027828177683 / 3808255243814215455080448000 : ℝ) * x ^ 5 +
    (-80960137610155113870752774977 / 5712382865721323182620672000 : ℝ) * x ^ 6 +
    (-2602561917875089185437680469 / 952063810953553863770112000 : ℝ) * x ^ 7 +
    (3372087235 / 1073741824 : ℝ) * x ^ 8 +
    (495698051702735309536849 / 595039881845971164856320 : ℝ) * x ^ 9 +
    (1741876333 / 1073741824 : ℝ) * x ^ 10

theorem Hn1_eq (x : ℝ) : Hn1 x = cf1.Hf x := by
  have g0 : h1_.getD 0 0 = (12338746989958058074460651520000 : Int) := rfl
  have g1 : h1_.getD 1 0 = (6169373494979029037230325760000 : Int) := rfl
  have g2 : h1_.getD 2 0 = (-111895860537357083012738984536800 : Int) := rfl
  have g3 : h1_.getD 3 0 = (-41235377189577934224488380684920 : Int) := rfl
  have g4 : h1_.getD 4 0 = (332645737569560698749538892069880 : Int) := rfl
  have g5 : h1_.getD 5 0 = (82840376012215871700326591385840 : Int) := rfl
  have g6 : h1_.getD 6 0 = (-349747794475870091921651987900640 : Int) := rfl
  have g7 : h1_.getD 7 0 = (-67458404911322311686544677756480 : Int) := rfl
  have g8 : h1_.getD 8 0 = (77499693670742662285040025600000 : Int) := rfl
  have g9 : h1_.getD 9 0 = (20557589600215838757112201728000 : Int) := rfl
  have g10 : h1_.getD 10 0 = (40033033789476249408987463680000 : Int) := rfl
  have e : cf1.Hf x = (∑ j ∈ Finset.range 11, ((h1_.getD j 0 : ℤ) : ℝ) * x ^ j) / ((lam_ : ℕ) : ℝ) := rfl
  rw [e]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10]
  unfold Hn1 lam_
  push_cast
  ring

/-- The `√3`-component of the minorant, in the monomial basis (exact rationals). -/
noncomputable def Hn2 (x : ℝ) : ℝ :=
    (0 : ℝ) +
    (0 : ℝ) * x +
    (36414004182076284294941945227 / 20564578316596763457434419200 : ℝ) * x ^ 2 +
    (-138523419587813377027293915227 / 34274297194327939095724032000 : ℝ) * x ^ 3 +
    (-251051730566211723567074311583 / 51411445791491908643586048000 : ℝ) * x ^ 4 +
    (268543412346820467436159061027 / 17137148597163969547862016000 : ℝ) * x ^ 5 +
    (11012767977873617751455553653 / 6426430723936488580448256000 : ℝ) * x ^ 6 +
    (-84508701532294463202255022061 / 4284287149290992386965504000 : ℝ) * x ^ 7 +
    (10211952757 / 2147483648 : ℝ) * x ^ 8 +
    (173790790657444454071426763 / 21421435746454961934827520 : ℝ) * x ^ 9 +
    (-896626767 / 268435456 : ℝ) * x ^ 10

theorem Hn2_eq (x : ℝ) : Hn2 x = cf2.Hf x := by
  have g0 : h2_.getD 0 0 = (0 : Int) := rfl
  have g1 : h2_.getD 1 0 = (0 : Int) := rfl
  have g2 : h2_.getD 2 0 = (43696805018491541153930334272400 : Int) := rfl
  have g3 : h2_.getD 3 0 = (-99736862103225631459651618963440 : Int) := rfl
  have g4 : h2_.getD 4 0 = (-120504830671781627312195669559840 : Int) := rfl
  have g5 : h2_.getD 5 0 = (386702513779421473108069047878880 : Int) := rfl
  have g6 : h2_.getD 6 0 = (42289029035034692165589326027520 : Int) := rfl
  have g7 : h2_.getD 7 0 = (-486770120826016108044988927071360 : Int) := rfl
  have g8 : h2_.getD 8 0 = (117349160222362393949045391360000 : Int) := rfl
  have g9 : h2_.getD 9 0 = (200206990837376011090283630976000 : Int) := rfl
  have g10 : h2_.getD 10 0 = (-82427641916551255262657249280000 : Int) := rfl
  have e : cf2.Hf x = (∑ j ∈ Finset.range 11, ((h2_.getD j 0 : ℤ) : ℝ) * x ^ j) / ((lam_ : ℕ) : ℝ) := rfl
  rw [e]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10]
  unfold Hn2 lam_
  push_cast
  ring

/-- The minorant over `K`: `Hn = Hn0 + √2 · Hn1 + √3 · Hn2`. -/
noncomputable def Hn (x : ℝ) : ℝ := Hn0 x + √2 * Hn1 x + √3 * Hn2 x

theorem HK_eq (x : ℝ) : Cert3K.HK 3 cfK w x = Hn x := by
  simp only [Cert3K.HK, Finset.sum_range_succ, Finset.sum_range_zero, w, List.getD_cons_zero,
    List.getD_cons_succ, Hn, Hn0_eq, Hn1_eq, Hn2_eq]
  simp only [cfK, List.getD_cons_zero, List.getD_cons_succ]
  ring

theorem eK_eq : Cert3K.eK 3 cfK w lam_ = 1 / 2 + 3 * √2 + √3 := by
  simp only [Cert3K.eK, Finset.sum_range_succ, Finset.sum_range_zero, w, List.getD_cons_zero,
    List.getD_cons_succ, cfK]
  have e0 : cf0.eps = eps0_ := rfl
  have e1 : cf1.eps = eps1_ := rfl
  have e2 : cf2.eps = eps2_ := rfl
  rw [e0, e1, e2]
  unfold eps0_ eps1_ eps2_ lam_
  push_cast
  ring

theorem hcf : ∀ c < 3, (cfK c).n = 5 ∧ (cfK c).Lam = lam_ ∧ (cfK c).an = -1 ∧ (cfK c).ad = 1 ∧
    (cfK c).K = 4 ∧ (cfK c).S.length = 8 ∧ chk (cfK c).idE = true := by
  intro c hc
  interval_cases c
  · exact ⟨rfl, rfl, rfl, rfl, rfl, rfl, cf0_chk⟩
  · exact ⟨rfl, rfl, rfl, rfl, rfl, rfl, cf1_chk⟩
  · exact ⟨rfl, rfl, rfl, rfl, rfl, rfl, cf2_chk⟩

theorem hm : ∀ c < 3, ∀ k < 4, (cfK c).m k = mF k := by decide +kernel

theorem hsh : ∀ c < 3, ∀ i < 8, ((cfK c).S.getD i Cert3K.sDflt).g = gs i ∧
    ((cfK c).S.getD i Cert3K.sDflt).σ = σs i ∧ ((cfK c).S.getD i Cert3K.sDflt).z = zs i := by
  decide +kernel

theorem hF0 : (Cert3K.FmK 3 cfK w lam_ mF 0).PosSemidef :=
  FmK_psd w_aff nF0_kok (fun c => [F0_D0, F0_D1, F0_D2].getD c [])
    (by intro c hc; interval_cases c <;> rfl)
    (by intro c hc; interval_cases c; exacts [F0_X0, F0_X1, F0_X2])
    (by intro c hc; interval_cases c; exacts [F0_sym0, F0_sym1, F0_sym2])
    nF0_mN

theorem hF1 : (Cert3K.FmK 3 cfK w lam_ mF 1).PosSemidef :=
  FmK_psd w_aff nF1_kok (fun c => [F1_D0, F1_D1, F1_D2].getD c [])
    (by intro c hc; interval_cases c <;> rfl)
    (by intro c hc; interval_cases c; exacts [F1_X0, F1_X1, F1_X2])
    (by intro c hc; interval_cases c; exacts [F1_sym0, F1_sym1, F1_sym2])
    nF1_mN

theorem hF2 : (Cert3K.FmK 3 cfK w lam_ mF 2).PosSemidef :=
  FmK_psd w_aff nF2_kok (fun c => [F2_D0, F2_D1, F2_D2].getD c [])
    (by intro c hc; interval_cases c <;> rfl)
    (by intro c hc; interval_cases c; exacts [F2_X0, F2_X1, F2_X2])
    (by intro c hc; interval_cases c; exacts [F2_sym0, F2_sym1, F2_sym2])
    nF2_mN

theorem hF3 : (Cert3K.FmK 3 cfK w lam_ mF 3).PosSemidef :=
  FmK_psd w_aff nF3_kok (fun c => [F3_D0, F3_D1, F3_D2].getD c [])
    (by intro c hc; interval_cases c <;> rfl)
    (by intro c hc; interval_cases c; exacts [F3_X0, F3_X1, F3_X2])
    (by intro c hc; interval_cases c; exacts [F3_sym0, F3_sym1, F3_sym2])
    nF3_mN

theorem hF : ∀ k < 4, (Cert3K.FmK 3 cfK w lam_ mF k).PosSemidef := by
  intro k hk
  interval_cases k
  · exact hF0
  · exact hF1
  · exact hF2
  · exact hF3

theorem hS0 (u v t : ℝ) :
    0 ≤ ∑ c ∈ Finset.range 3, w c * (sqfE ((cfK c).S.getD 0 Cert3K.sDflt).B (zs 0)).ev u v t :=
  sqf_nonneg w_aff nS0_kok (fun c => ((cfK c).S.getD 0 Cert3K.sDflt).B)
    (by
      intro c hc
      interval_cases c
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S0_X0
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S0_X1
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S0_X2)
    (zs 0) (by decide +kernel) u v t

theorem hS1 (u v t : ℝ) :
    0 ≤ ∑ c ∈ Finset.range 3, w c * (sqfE ((cfK c).S.getD 1 Cert3K.sDflt).B (zs 1)).ev u v t :=
  sqf_nonneg w_aff nS1_kok (fun c => ((cfK c).S.getD 1 Cert3K.sDflt).B)
    (by
      intro c hc
      interval_cases c
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S1_X0
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S1_X1
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S1_X2)
    (zs 1) (by decide +kernel) u v t

theorem hS2 (u v t : ℝ) :
    0 ≤ ∑ c ∈ Finset.range 3, w c * (sqfE ((cfK c).S.getD 2 Cert3K.sDflt).B (zs 2)).ev u v t :=
  sqf_nonneg w_aff nS2_kok (fun c => ((cfK c).S.getD 2 Cert3K.sDflt).B)
    (by
      intro c hc
      interval_cases c
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S2_X0
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S2_X1
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S2_X2)
    (zs 2) (by decide +kernel) u v t

theorem hS3 (u v t : ℝ) :
    0 ≤ ∑ c ∈ Finset.range 3, w c * (sqfE ((cfK c).S.getD 3 Cert3K.sDflt).B (zs 3)).ev u v t :=
  sqf_nonneg w_aff nS3_kok (fun c => ((cfK c).S.getD 3 Cert3K.sDflt).B)
    (by
      intro c hc
      interval_cases c
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S3_X0
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S3_X1
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S3_X2)
    (zs 3) (by decide +kernel) u v t

theorem hS4 (u v t : ℝ) :
    0 ≤ ∑ c ∈ Finset.range 3, w c * (sqfE ((cfK c).S.getD 4 Cert3K.sDflt).B (zs 4)).ev u v t :=
  sqf_nonneg w_aff nS4_kok (fun c => ((cfK c).S.getD 4 Cert3K.sDflt).B)
    (by
      intro c hc
      interval_cases c
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S4_X0
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S4_X1
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S4_X2)
    (zs 4) (by decide +kernel) u v t

theorem hS5 (u v t : ℝ) :
    0 ≤ ∑ c ∈ Finset.range 3, w c * (sqfE ((cfK c).S.getD 5 Cert3K.sDflt).B (zs 5)).ev u v t :=
  sqf_nonneg w_aff nS5_kok (fun c => ((cfK c).S.getD 5 Cert3K.sDflt).B)
    (by
      intro c hc
      interval_cases c
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S5_X0
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S5_X1
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S5_X2)
    (zs 5) (by decide +kernel) u v t

theorem hS6 (u v t : ℝ) :
    0 ≤ ∑ c ∈ Finset.range 3, w c * (sqfE ((cfK c).S.getD 6 Cert3K.sDflt).B (zs 6)).ev u v t :=
  sqf_nonneg w_aff nS6_kok (fun c => ((cfK c).S.getD 6 Cert3K.sDflt).B)
    (by
      intro c hc
      interval_cases c
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S6_X0
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S6_X1
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S6_X2)
    (zs 6) (by decide +kernel) u v t

theorem hS7 (u v t : ℝ) :
    0 ≤ ∑ c ∈ Finset.range 3, w c * (sqfE ((cfK c).S.getD 7 Cert3K.sDflt).B (zs 7)).ev u v t :=
  sqf_nonneg w_aff nS7_kok (fun c => ((cfK c).S.getD 7 Cert3K.sDflt).B)
    (by
      intro c hc
      interval_cases c
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S7_X0
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S7_X1
      · exact congrArg (fun X => (⟨[], [], X⟩ : Blk)) S7_X2)
    (zs 7) (by decide +kernel) u v t

theorem hS : ∀ i < 8, ∀ u v t : ℝ,
    0 ≤ ∑ c ∈ Finset.range 3, w c * (sqfE ((cfK c).S.getD i Cert3K.sDflt).B (zs i)).ev u v t := by
  intro i hi
  interval_cases i
  · exact hS0
  · exact hS1
  · exact hS2
  · exact hS3
  · exact hS4
  · exact hS5
  · exact hS6
  · exact hS7

/-- **The three-point bound for `N = 5`, Coulomb.**  For all unit vectors `x 0, …, x 4` of `ℝ³`,
`1/2 + 3√2 + √3 ≤ ∑_{i<j} Hn ⟪x i, x j⟫`. -/
theorem bound (x : Fin 5 → R3) (hx : ∀ i, ‖x i‖ = 1) :
    (1 / 2 + 3 * √2 + √3 : ℝ) ≤ ∑ i, ∑ j ∈ Finset.Ioi i, Hn ⟪x i, x j⟫ := by
  have h := Cert3K.soundK 3 cfK w 5 lam_ 4 8 mF gs σs zs (by norm_num) (by decide +kernel)
    hcf hm hsh hF hS x hx
  rw [eK_eq] at h
  simp only [HK_eq] at h
  exact h

end N5R1
