import ThomsonGen.Case1Stat
import N5R1.ChkI0
import N5R1.ChkI1
import N5R1.ChkI2
import N5R1.ChkF
import N5R1.ChkS0a
import N5R1.ChkS0b
import N5R1.ChkS1
import N5R1.ChkS2
import N5R1.ChkS3
import N5R1.ChkS4
import N5R1.ChkS5
import N5R1.ChkS6
import N5R1.ChkS7
/-! N = 5, Coulomb (s = 1): assembly of the chunked identity checks `chk cf<c>.idE = true` (`c = 0, 1, 2`;
the composition mirrors upstream `Case1.lean`).

Attribution: adapted from huwngtran/thomson-n7-lean @ 25f2fa5, `ThomsonN7/Solution.lean` (ours ← upstream): `cf0_chk`, `cf1_chk`, `cf2_chk` ← `Case1.cf_chk`.

Generated by `lean/gen/emit_n5_s1.py` from `cert_n5_s1_short.json`
(sha256 66c5baa88a130761295e1a161f9fe35f8218c28e3defddc67ad22bcd5361e2e0).  Do not edit; regenerate. -/

namespace N5R1
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.Cert.Cert3 ThomsonN7.Cert.KB

-- large literals: elaboration budget only (no effect on what is checked)
set_option maxHeartbeats 0

theorem range_K : List.range 4 = [0, 1, 2, 3] := rfl

theorem cf0_K : cf0.K = 4 := rfl

theorem cf0_S : cf0.S = [S0_0, S1_0, S2_0, S3_0, S4_0, S5_0, S6_0, S7_0] := rfl

/-- The statistics of the identity expression of `cf0`. -/
theorem idE_stat0 : ThomsonN7.Case1.c1Stat 125 11 cf0.idE = (22110553068442175856220371011081628000, 10, 10, 10, (0 : Int)) := by
  rw [ThomsonN7.Case1.c1Stat_idE, cf0_K, cf0_S, range_K]
  simp only [List.map_cons, List.map_nil]
  rw [stat_H_0, stat_F0_0, stat_F1_0, stat_F2_0, stat_F3_0, stat_S0_0, stat_S1_0, stat_S2_0, stat_S3_0, stat_S4_0, stat_S5_0, stat_S6_0, stat_S7_0]
  decide +kernel

/-- The Kronecker check of the identity of `cf0`. -/
theorem cf0_chk : chk cf0.idE = true := by
  have h := ThomsonN7.Case1.c1Stat_eq 125 11 cf0.idE
  rw [idE_stat0] at h
  simp only [Prod.mk.injEq] at h
  obtain ⟨hl, hx, hy, hz, hk⟩ := h
  unfold chk
  rw [← hl, ← hx, ← hy, ← hz]
  have hW : Nat.log2 22110553068442175856220371011081628000 + 1 = 125 := by decide +kernel
  have hD : max 10 (max 10 10) + 1 = 11 := by decide +kernel
  rw [hW, hD]
  exact decide_eq_true hk.symm

theorem cf1_K : cf1.K = 4 := rfl

theorem cf1_S : cf1.S = [S0_1, S1_1, S2_1, S3_1, S4_1, S5_1, S6_1, S7_1] := rfl

/-- The statistics of the identity expression of `cf1`. -/
theorem idE_stat1 : ThomsonN7.Case1.c1Stat 125 11 cf1.idE = (28033886060575556504933551915728100800, 10, 10, 10, (0 : Int)) := by
  rw [ThomsonN7.Case1.c1Stat_idE, cf1_K, cf1_S, range_K]
  simp only [List.map_cons, List.map_nil]
  rw [stat_H_1, stat_F0_1, stat_F1_1, stat_F2_1, stat_F3_1, stat_S0_1, stat_S1_1, stat_S2_1, stat_S3_1, stat_S4_1, stat_S5_1, stat_S6_1, stat_S7_1]
  decide +kernel

/-- The Kronecker check of the identity of `cf1`. -/
theorem cf1_chk : chk cf1.idE = true := by
  have h := ThomsonN7.Case1.c1Stat_eq 125 11 cf1.idE
  rw [idE_stat1] at h
  simp only [Prod.mk.injEq] at h
  obtain ⟨hl, hx, hy, hz, hk⟩ := h
  unfold chk
  rw [← hl, ← hx, ← hy, ← hz]
  have hW : Nat.log2 28033886060575556504933551915728100800 + 1 = 125 := by decide +kernel
  have hD : max 10 (max 10 10) + 1 = 11 := by decide +kernel
  rw [hW, hD]
  exact decide_eq_true hk.symm

theorem cf2_K : cf2.K = 4 := rfl

theorem cf2_S : cf2.S = [S0_2, S1_2, S2_2, S3_2, S4_2, S5_2, S6_2, S7_2] := rfl

/-- The statistics of the identity expression of `cf2`. -/
theorem idE_stat2 : ThomsonN7.Case1.c1Stat 125 11 cf2.idE = (30727903477195617777369841197549484800, 10, 10, 10, (0 : Int)) := by
  rw [ThomsonN7.Case1.c1Stat_idE, cf2_K, cf2_S, range_K]
  simp only [List.map_cons, List.map_nil]
  rw [stat_H_2, stat_F0_2, stat_F1_2, stat_F2_2, stat_F3_2, stat_S0_2, stat_S1_2, stat_S2_2, stat_S3_2, stat_S4_2, stat_S5_2, stat_S6_2, stat_S7_2]
  decide +kernel

/-- The Kronecker check of the identity of `cf2`. -/
theorem cf2_chk : chk cf2.idE = true := by
  have h := ThomsonN7.Case1.c1Stat_eq 125 11 cf2.idE
  rw [idE_stat2] at h
  simp only [Prod.mk.injEq] at h
  obtain ⟨hl, hx, hy, hz, hk⟩ := h
  unfold chk
  rw [← hl, ← hx, ← hy, ← hz]
  have hW : Nat.log2 30727903477195617777369841197549484800 + 1 = 125 := by decide +kernel
  have hD : max 10 (max 10 10) + 1 = 11 := by decide +kernel
  rw [hW, hD]
  exact decide_eq_true hk.symm

end N5R1
