import N5R1.Data
import N5R1.Blocks
/-! N = 5, Coulomb (s = 1): the kernel blocks `F0..F3`.  Expanded component blocks `= Ñ·E_c·Ñᵀ` and symmetric;
the `K`-blocks with their corner witnesses (`KOK`).

Generated by `lean/gen/emit_n5_s1.py` from `cert_n5_s1_short.json`
(sha256 66c5baa88a130761295e1a161f9fe35f8218c28e3defddc67ad22bcd5361e2e0).  Do not edit; regenerate. -/

namespace N5R1
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.Cert.Cert3 ThomsonN7.Cert.KB

-- large literals: elaboration budget only (no effect on what is checked)
set_option maxHeartbeats 0

theorem F0_X0 : F0_D0 = expandE nF0_N nF0_E0 := by decide +kernel
theorem F0_sym0 : F0_D0.map (List.take 6) = transposeSq 6 F0_D0 := by decide +kernel
theorem F0_X1 : F0_D1 = expandE nF0_N nF0_E1 := by decide +kernel
theorem F0_sym1 : F0_D1.map (List.take 6) = transposeSq 6 F0_D1 := by decide +kernel
theorem F0_X2 : F0_D2 = expandE nF0_N nF0_E2 := by decide +kernel
theorem F0_sym2 : F0_D2.map (List.take 6) = transposeSq 6 F0_D2 := by decide +kernel
theorem nF0_hP : NBlk.ldl nF0_d nF0_l = nF0_P := by decide +kernel
theorem nF0_ok0 : okF 4 nF0_C0 = true := by decide +kernel
theorem nF0_lin0 : NBlk.matAdd nF0_P nF0_R0 = lin κ0 nF0_Es := by decide +kernel
theorem nF0_corner0 : CornerOK 3 4 nF0_Es κ0 nF0_C0 :=
  ⟨by decide +kernel, nF0_ok0, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF0_C0 = NBlk.matAdd (NBlk.ldl nF0_d nF0_l) nF0_R0 from rfl, nF0_hP]
    exact nF0_lin0⟩
theorem nF0_ok1 : okF 4 nF0_C1 = true := by decide +kernel
theorem nF0_lin1 : NBlk.matAdd nF0_P nF0_R1 = lin κ1 nF0_Es := by decide +kernel
theorem nF0_corner1 : CornerOK 3 4 nF0_Es κ1 nF0_C1 :=
  ⟨by decide +kernel, nF0_ok1, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF0_C1 = NBlk.matAdd (NBlk.ldl nF0_d nF0_l) nF0_R1 from rfl, nF0_hP]
    exact nF0_lin1⟩
theorem nF0_ok2 : okF 4 nF0_C2 = true := by decide +kernel
theorem nF0_lin2 : NBlk.matAdd nF0_P nF0_R2 = lin κ2 nF0_Es := by decide +kernel
theorem nF0_corner2 : CornerOK 3 4 nF0_Es κ2 nF0_C2 :=
  ⟨by decide +kernel, nF0_ok2, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF0_C2 = NBlk.matAdd (NBlk.ldl nF0_d nF0_l) nF0_R2 from rfl, nF0_hP]
    exact nF0_lin2⟩
theorem nF0_ok3 : okF 4 nF0_C3 = true := by decide +kernel
theorem nF0_lin3 : NBlk.matAdd nF0_P nF0_R3 = lin κ3 nF0_Es := by decide +kernel
theorem nF0_corner3 : CornerOK 3 4 nF0_Es κ3 nF0_C3 :=
  ⟨by decide +kernel, nF0_ok3, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF0_C3 = NBlk.matAdd (NBlk.ldl nF0_d nF0_l) nF0_R3 from rfl, nF0_hP]
    exact nF0_lin3⟩
/-- The checked `K`-block `F0`. -/
theorem nF0_kok : KOK 3 4 κs nF0_N nF0_Es [nF0_C0, nF0_C1, nF0_C2, nF0_C3] :=
  ⟨by decide +kernel, by decide +kernel, by decide +kernel,
    .cons nF0_corner0 (.cons nF0_corner1 (.cons nF0_corner2 (.cons nF0_corner3 .nil)))⟩
theorem nF0_mN : 6 ≤ nF0_N.length := by decide +kernel

theorem F1_X0 : F1_D0 = expandE nF1_N nF1_E0 := by decide +kernel
theorem F1_sym0 : F1_D0.map (List.take 5) = transposeSq 5 F1_D0 := by decide +kernel
theorem F1_X1 : F1_D1 = expandE nF1_N nF1_E1 := by decide +kernel
theorem F1_sym1 : F1_D1.map (List.take 5) = transposeSq 5 F1_D1 := by decide +kernel
theorem F1_X2 : F1_D2 = expandE nF1_N nF1_E2 := by decide +kernel
theorem F1_sym2 : F1_D2.map (List.take 5) = transposeSq 5 F1_D2 := by decide +kernel
theorem nF1_hP : NBlk.ldl nF1_d nF1_l = nF1_P := by decide +kernel
theorem nF1_ok0 : okF 5 nF1_C0 = true := by decide +kernel
theorem nF1_lin0 : NBlk.matAdd nF1_P nF1_R0 = lin κ0 nF1_Es := by decide +kernel
theorem nF1_corner0 : CornerOK 3 5 nF1_Es κ0 nF1_C0 :=
  ⟨by decide +kernel, nF1_ok0, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF1_C0 = NBlk.matAdd (NBlk.ldl nF1_d nF1_l) nF1_R0 from rfl, nF1_hP]
    exact nF1_lin0⟩
theorem nF1_ok1 : okF 5 nF1_C1 = true := by decide +kernel
theorem nF1_lin1 : NBlk.matAdd nF1_P nF1_R1 = lin κ1 nF1_Es := by decide +kernel
theorem nF1_corner1 : CornerOK 3 5 nF1_Es κ1 nF1_C1 :=
  ⟨by decide +kernel, nF1_ok1, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF1_C1 = NBlk.matAdd (NBlk.ldl nF1_d nF1_l) nF1_R1 from rfl, nF1_hP]
    exact nF1_lin1⟩
theorem nF1_ok2 : okF 5 nF1_C2 = true := by decide +kernel
theorem nF1_lin2 : NBlk.matAdd nF1_P nF1_R2 = lin κ2 nF1_Es := by decide +kernel
theorem nF1_corner2 : CornerOK 3 5 nF1_Es κ2 nF1_C2 :=
  ⟨by decide +kernel, nF1_ok2, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF1_C2 = NBlk.matAdd (NBlk.ldl nF1_d nF1_l) nF1_R2 from rfl, nF1_hP]
    exact nF1_lin2⟩
theorem nF1_ok3 : okF 5 nF1_C3 = true := by decide +kernel
theorem nF1_lin3 : NBlk.matAdd nF1_P nF1_R3 = lin κ3 nF1_Es := by decide +kernel
theorem nF1_corner3 : CornerOK 3 5 nF1_Es κ3 nF1_C3 :=
  ⟨by decide +kernel, nF1_ok3, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF1_C3 = NBlk.matAdd (NBlk.ldl nF1_d nF1_l) nF1_R3 from rfl, nF1_hP]
    exact nF1_lin3⟩
/-- The checked `K`-block `F1`. -/
theorem nF1_kok : KOK 3 5 κs nF1_N nF1_Es [nF1_C0, nF1_C1, nF1_C2, nF1_C3] :=
  ⟨by decide +kernel, by decide +kernel, by decide +kernel,
    .cons nF1_corner0 (.cons nF1_corner1 (.cons nF1_corner2 (.cons nF1_corner3 .nil)))⟩
theorem nF1_mN : 5 ≤ nF1_N.length := by decide +kernel

theorem F2_X0 : F2_D0 = expandE nF2_N nF2_E0 := by decide +kernel
theorem F2_sym0 : F2_D0.map (List.take 4) = transposeSq 4 F2_D0 := by decide +kernel
theorem F2_X1 : F2_D1 = expandE nF2_N nF2_E1 := by decide +kernel
theorem F2_sym1 : F2_D1.map (List.take 4) = transposeSq 4 F2_D1 := by decide +kernel
theorem F2_X2 : F2_D2 = expandE nF2_N nF2_E2 := by decide +kernel
theorem F2_sym2 : F2_D2.map (List.take 4) = transposeSq 4 F2_D2 := by decide +kernel
theorem nF2_hP : NBlk.ldl nF2_d nF2_l = nF2_P := by decide +kernel
theorem nF2_ok0 : okF 3 nF2_C0 = true := by decide +kernel
theorem nF2_lin0 : NBlk.matAdd nF2_P nF2_R0 = lin κ0 nF2_Es := by decide +kernel
theorem nF2_corner0 : CornerOK 3 3 nF2_Es κ0 nF2_C0 :=
  ⟨by decide +kernel, nF2_ok0, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF2_C0 = NBlk.matAdd (NBlk.ldl nF2_d nF2_l) nF2_R0 from rfl, nF2_hP]
    exact nF2_lin0⟩
theorem nF2_ok1 : okF 3 nF2_C1 = true := by decide +kernel
theorem nF2_lin1 : NBlk.matAdd nF2_P nF2_R1 = lin κ1 nF2_Es := by decide +kernel
theorem nF2_corner1 : CornerOK 3 3 nF2_Es κ1 nF2_C1 :=
  ⟨by decide +kernel, nF2_ok1, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF2_C1 = NBlk.matAdd (NBlk.ldl nF2_d nF2_l) nF2_R1 from rfl, nF2_hP]
    exact nF2_lin1⟩
theorem nF2_ok2 : okF 3 nF2_C2 = true := by decide +kernel
theorem nF2_lin2 : NBlk.matAdd nF2_P nF2_R2 = lin κ2 nF2_Es := by decide +kernel
theorem nF2_corner2 : CornerOK 3 3 nF2_Es κ2 nF2_C2 :=
  ⟨by decide +kernel, nF2_ok2, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF2_C2 = NBlk.matAdd (NBlk.ldl nF2_d nF2_l) nF2_R2 from rfl, nF2_hP]
    exact nF2_lin2⟩
theorem nF2_ok3 : okF 3 nF2_C3 = true := by decide +kernel
theorem nF2_lin3 : NBlk.matAdd nF2_P nF2_R3 = lin κ3 nF2_Es := by decide +kernel
theorem nF2_corner3 : CornerOK 3 3 nF2_Es κ3 nF2_C3 :=
  ⟨by decide +kernel, nF2_ok3, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF2_C3 = NBlk.matAdd (NBlk.ldl nF2_d nF2_l) nF2_R3 from rfl, nF2_hP]
    exact nF2_lin3⟩
/-- The checked `K`-block `F2`. -/
theorem nF2_kok : KOK 3 3 κs nF2_N nF2_Es [nF2_C0, nF2_C1, nF2_C2, nF2_C3] :=
  ⟨by decide +kernel, by decide +kernel, by decide +kernel,
    .cons nF2_corner0 (.cons nF2_corner1 (.cons nF2_corner2 (.cons nF2_corner3 .nil)))⟩
theorem nF2_mN : 4 ≤ nF2_N.length := by decide +kernel

theorem F3_X0 : F3_D0 = expandE nF3_N nF3_E0 := by decide +kernel
theorem F3_sym0 : F3_D0.map (List.take 3) = transposeSq 3 F3_D0 := by decide +kernel
theorem F3_X1 : F3_D1 = expandE nF3_N nF3_E1 := by decide +kernel
theorem F3_sym1 : F3_D1.map (List.take 3) = transposeSq 3 F3_D1 := by decide +kernel
theorem F3_X2 : F3_D2 = expandE nF3_N nF3_E2 := by decide +kernel
theorem F3_sym2 : F3_D2.map (List.take 3) = transposeSq 3 F3_D2 := by decide +kernel
theorem nF3_hP : NBlk.ldl nF3_d nF3_l = nF3_P := by decide +kernel
theorem nF3_ok0 : okF 2 nF3_C0 = true := by decide +kernel
theorem nF3_lin0 : NBlk.matAdd nF3_P nF3_R0 = lin κ0 nF3_Es := by decide +kernel
theorem nF3_corner0 : CornerOK 3 2 nF3_Es κ0 nF3_C0 :=
  ⟨by decide +kernel, nF3_ok0, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF3_C0 = NBlk.matAdd (NBlk.ldl nF3_d nF3_l) nF3_R0 from rfl, nF3_hP]
    exact nF3_lin0⟩
theorem nF3_ok1 : okF 2 nF3_C1 = true := by decide +kernel
theorem nF3_lin1 : NBlk.matAdd nF3_P nF3_R1 = lin κ1 nF3_Es := by decide +kernel
theorem nF3_corner1 : CornerOK 3 2 nF3_Es κ1 nF3_C1 :=
  ⟨by decide +kernel, nF3_ok1, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF3_C1 = NBlk.matAdd (NBlk.ldl nF3_d nF3_l) nF3_R1 from rfl, nF3_hP]
    exact nF3_lin1⟩
theorem nF3_ok2 : okF 2 nF3_C2 = true := by decide +kernel
theorem nF3_lin2 : NBlk.matAdd nF3_P nF3_R2 = lin κ2 nF3_Es := by decide +kernel
theorem nF3_corner2 : CornerOK 3 2 nF3_Es κ2 nF3_C2 :=
  ⟨by decide +kernel, nF3_ok2, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF3_C2 = NBlk.matAdd (NBlk.ldl nF3_d nF3_l) nF3_R2 from rfl, nF3_hP]
    exact nF3_lin2⟩
theorem nF3_ok3 : okF 2 nF3_C3 = true := by decide +kernel
theorem nF3_lin3 : NBlk.matAdd nF3_P nF3_R3 = lin κ3 nF3_Es := by decide +kernel
theorem nF3_corner3 : CornerOK 3 2 nF3_Es κ3 nF3_C3 :=
  ⟨by decide +kernel, nF3_ok3, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nF3_C3 = NBlk.matAdd (NBlk.ldl nF3_d nF3_l) nF3_R3 from rfl, nF3_hP]
    exact nF3_lin3⟩
/-- The checked `K`-block `F3`. -/
theorem nF3_kok : KOK 3 2 κs nF3_N nF3_Es [nF3_C0, nF3_C1, nF3_C2, nF3_C3] :=
  ⟨by decide +kernel, by decide +kernel, by decide +kernel,
    .cons nF3_corner0 (.cons nF3_corner1 (.cons nF3_corner2 (.cons nF3_corner3 .nil)))⟩
theorem nF3_mN : 3 ≤ nF3_N.length := by decide +kernel

end N5R1
