import N5R1.Data
import N5R1.Blocks
/-! N = 5, Coulomb (s = 1): SOS block `S4` (35 × 28).  The expanded component blocks are `Ñ·E_c·Ñᵀ`
(row by row), and the `K`-block with its corner witnesses (`KOK`; `ldl d l = P` row by row).

Generated by `lean/gen/emit_n5_s1.py` from `cert_n5_s1_short.json`
(sha256 66c5baa88a130761295e1a161f9fe35f8218c28e3defddc67ad22bcd5361e2e0).  Do not edit; regenerate. -/

namespace N5R1
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.Cert.Cert3 ThomsonN7.Cert.KB

-- large literals: elaboration budget only (no effect on what is checked)
set_option maxHeartbeats 0

theorem S4_Dl0 : S4_D0.length = 35 := by decide +kernel
theorem S4_Xl0 : (expandE nS4_N nS4_E0).length = 35 := by decide +kernel
theorem S4_X0_0 : S4_D0.getD 0 [] = (expandE nS4_N nS4_E0).getD 0 [] := by decide +kernel
theorem S4_X0_1 : S4_D0.getD 1 [] = (expandE nS4_N nS4_E0).getD 1 [] := by decide +kernel
theorem S4_X0_2 : S4_D0.getD 2 [] = (expandE nS4_N nS4_E0).getD 2 [] := by decide +kernel
theorem S4_X0_3 : S4_D0.getD 3 [] = (expandE nS4_N nS4_E0).getD 3 [] := by decide +kernel
theorem S4_X0_4 : S4_D0.getD 4 [] = (expandE nS4_N nS4_E0).getD 4 [] := by decide +kernel
theorem S4_X0_5 : S4_D0.getD 5 [] = (expandE nS4_N nS4_E0).getD 5 [] := by decide +kernel
theorem S4_X0_6 : S4_D0.getD 6 [] = (expandE nS4_N nS4_E0).getD 6 [] := by decide +kernel
theorem S4_X0_7 : S4_D0.getD 7 [] = (expandE nS4_N nS4_E0).getD 7 [] := by decide +kernel
theorem S4_X0_8 : S4_D0.getD 8 [] = (expandE nS4_N nS4_E0).getD 8 [] := by decide +kernel
theorem S4_X0_9 : S4_D0.getD 9 [] = (expandE nS4_N nS4_E0).getD 9 [] := by decide +kernel
theorem S4_X0_10 : S4_D0.getD 10 [] = (expandE nS4_N nS4_E0).getD 10 [] := by decide +kernel
theorem S4_X0_11 : S4_D0.getD 11 [] = (expandE nS4_N nS4_E0).getD 11 [] := by decide +kernel
theorem S4_X0_12 : S4_D0.getD 12 [] = (expandE nS4_N nS4_E0).getD 12 [] := by decide +kernel
theorem S4_X0_13 : S4_D0.getD 13 [] = (expandE nS4_N nS4_E0).getD 13 [] := by decide +kernel
theorem S4_X0_14 : S4_D0.getD 14 [] = (expandE nS4_N nS4_E0).getD 14 [] := by decide +kernel
theorem S4_X0_15 : S4_D0.getD 15 [] = (expandE nS4_N nS4_E0).getD 15 [] := by decide +kernel
theorem S4_X0_16 : S4_D0.getD 16 [] = (expandE nS4_N nS4_E0).getD 16 [] := by decide +kernel
theorem S4_X0_17 : S4_D0.getD 17 [] = (expandE nS4_N nS4_E0).getD 17 [] := by decide +kernel
theorem S4_X0_18 : S4_D0.getD 18 [] = (expandE nS4_N nS4_E0).getD 18 [] := by decide +kernel
theorem S4_X0_19 : S4_D0.getD 19 [] = (expandE nS4_N nS4_E0).getD 19 [] := by decide +kernel
theorem S4_X0_20 : S4_D0.getD 20 [] = (expandE nS4_N nS4_E0).getD 20 [] := by decide +kernel
theorem S4_X0_21 : S4_D0.getD 21 [] = (expandE nS4_N nS4_E0).getD 21 [] := by decide +kernel
theorem S4_X0_22 : S4_D0.getD 22 [] = (expandE nS4_N nS4_E0).getD 22 [] := by decide +kernel
theorem S4_X0_23 : S4_D0.getD 23 [] = (expandE nS4_N nS4_E0).getD 23 [] := by decide +kernel
theorem S4_X0_24 : S4_D0.getD 24 [] = (expandE nS4_N nS4_E0).getD 24 [] := by decide +kernel
theorem S4_X0_25 : S4_D0.getD 25 [] = (expandE nS4_N nS4_E0).getD 25 [] := by decide +kernel
theorem S4_X0_26 : S4_D0.getD 26 [] = (expandE nS4_N nS4_E0).getD 26 [] := by decide +kernel
theorem S4_X0_27 : S4_D0.getD 27 [] = (expandE nS4_N nS4_E0).getD 27 [] := by decide +kernel
theorem S4_X0_28 : S4_D0.getD 28 [] = (expandE nS4_N nS4_E0).getD 28 [] := by decide +kernel
theorem S4_X0_29 : S4_D0.getD 29 [] = (expandE nS4_N nS4_E0).getD 29 [] := by decide +kernel
theorem S4_X0_30 : S4_D0.getD 30 [] = (expandE nS4_N nS4_E0).getD 30 [] := by decide +kernel
theorem S4_X0_31 : S4_D0.getD 31 [] = (expandE nS4_N nS4_E0).getD 31 [] := by decide +kernel
theorem S4_X0_32 : S4_D0.getD 32 [] = (expandE nS4_N nS4_E0).getD 32 [] := by decide +kernel
theorem S4_X0_33 : S4_D0.getD 33 [] = (expandE nS4_N nS4_E0).getD 33 [] := by decide +kernel
theorem S4_X0_34 : S4_D0.getD 34 [] = (expandE nS4_N nS4_E0).getD 34 [] := by decide +kernel

theorem S4_X0 : S4_D0 = expandE nS4_N nS4_E0 :=
  NBlk.eq_of_getD_rows (S4_Dl0.trans S4_Xl0.symm) fun a ha => by
    rw [S4_Dl0] at ha
    exact match a, ha with
      | 0, _ => S4_X0_0
      | 1, _ => S4_X0_1
      | 2, _ => S4_X0_2
      | 3, _ => S4_X0_3
      | 4, _ => S4_X0_4
      | 5, _ => S4_X0_5
      | 6, _ => S4_X0_6
      | 7, _ => S4_X0_7
      | 8, _ => S4_X0_8
      | 9, _ => S4_X0_9
      | 10, _ => S4_X0_10
      | 11, _ => S4_X0_11
      | 12, _ => S4_X0_12
      | 13, _ => S4_X0_13
      | 14, _ => S4_X0_14
      | 15, _ => S4_X0_15
      | 16, _ => S4_X0_16
      | 17, _ => S4_X0_17
      | 18, _ => S4_X0_18
      | 19, _ => S4_X0_19
      | 20, _ => S4_X0_20
      | 21, _ => S4_X0_21
      | 22, _ => S4_X0_22
      | 23, _ => S4_X0_23
      | 24, _ => S4_X0_24
      | 25, _ => S4_X0_25
      | 26, _ => S4_X0_26
      | 27, _ => S4_X0_27
      | 28, _ => S4_X0_28
      | 29, _ => S4_X0_29
      | 30, _ => S4_X0_30
      | 31, _ => S4_X0_31
      | 32, _ => S4_X0_32
      | 33, _ => S4_X0_33
      | 34, _ => S4_X0_34
      | _ + 35, h => absurd h (by omega)

theorem S4_Dl1 : S4_D1.length = 35 := by decide +kernel
theorem S4_Xl1 : (expandE nS4_N nS4_E1).length = 35 := by decide +kernel
theorem S4_X1_0 : S4_D1.getD 0 [] = (expandE nS4_N nS4_E1).getD 0 [] := by decide +kernel
theorem S4_X1_1 : S4_D1.getD 1 [] = (expandE nS4_N nS4_E1).getD 1 [] := by decide +kernel
theorem S4_X1_2 : S4_D1.getD 2 [] = (expandE nS4_N nS4_E1).getD 2 [] := by decide +kernel
theorem S4_X1_3 : S4_D1.getD 3 [] = (expandE nS4_N nS4_E1).getD 3 [] := by decide +kernel
theorem S4_X1_4 : S4_D1.getD 4 [] = (expandE nS4_N nS4_E1).getD 4 [] := by decide +kernel
theorem S4_X1_5 : S4_D1.getD 5 [] = (expandE nS4_N nS4_E1).getD 5 [] := by decide +kernel
theorem S4_X1_6 : S4_D1.getD 6 [] = (expandE nS4_N nS4_E1).getD 6 [] := by decide +kernel
theorem S4_X1_7 : S4_D1.getD 7 [] = (expandE nS4_N nS4_E1).getD 7 [] := by decide +kernel
theorem S4_X1_8 : S4_D1.getD 8 [] = (expandE nS4_N nS4_E1).getD 8 [] := by decide +kernel
theorem S4_X1_9 : S4_D1.getD 9 [] = (expandE nS4_N nS4_E1).getD 9 [] := by decide +kernel
theorem S4_X1_10 : S4_D1.getD 10 [] = (expandE nS4_N nS4_E1).getD 10 [] := by decide +kernel
theorem S4_X1_11 : S4_D1.getD 11 [] = (expandE nS4_N nS4_E1).getD 11 [] := by decide +kernel
theorem S4_X1_12 : S4_D1.getD 12 [] = (expandE nS4_N nS4_E1).getD 12 [] := by decide +kernel
theorem S4_X1_13 : S4_D1.getD 13 [] = (expandE nS4_N nS4_E1).getD 13 [] := by decide +kernel
theorem S4_X1_14 : S4_D1.getD 14 [] = (expandE nS4_N nS4_E1).getD 14 [] := by decide +kernel
theorem S4_X1_15 : S4_D1.getD 15 [] = (expandE nS4_N nS4_E1).getD 15 [] := by decide +kernel
theorem S4_X1_16 : S4_D1.getD 16 [] = (expandE nS4_N nS4_E1).getD 16 [] := by decide +kernel
theorem S4_X1_17 : S4_D1.getD 17 [] = (expandE nS4_N nS4_E1).getD 17 [] := by decide +kernel
theorem S4_X1_18 : S4_D1.getD 18 [] = (expandE nS4_N nS4_E1).getD 18 [] := by decide +kernel
theorem S4_X1_19 : S4_D1.getD 19 [] = (expandE nS4_N nS4_E1).getD 19 [] := by decide +kernel
theorem S4_X1_20 : S4_D1.getD 20 [] = (expandE nS4_N nS4_E1).getD 20 [] := by decide +kernel
theorem S4_X1_21 : S4_D1.getD 21 [] = (expandE nS4_N nS4_E1).getD 21 [] := by decide +kernel
theorem S4_X1_22 : S4_D1.getD 22 [] = (expandE nS4_N nS4_E1).getD 22 [] := by decide +kernel
theorem S4_X1_23 : S4_D1.getD 23 [] = (expandE nS4_N nS4_E1).getD 23 [] := by decide +kernel
theorem S4_X1_24 : S4_D1.getD 24 [] = (expandE nS4_N nS4_E1).getD 24 [] := by decide +kernel
theorem S4_X1_25 : S4_D1.getD 25 [] = (expandE nS4_N nS4_E1).getD 25 [] := by decide +kernel
theorem S4_X1_26 : S4_D1.getD 26 [] = (expandE nS4_N nS4_E1).getD 26 [] := by decide +kernel
theorem S4_X1_27 : S4_D1.getD 27 [] = (expandE nS4_N nS4_E1).getD 27 [] := by decide +kernel
theorem S4_X1_28 : S4_D1.getD 28 [] = (expandE nS4_N nS4_E1).getD 28 [] := by decide +kernel
theorem S4_X1_29 : S4_D1.getD 29 [] = (expandE nS4_N nS4_E1).getD 29 [] := by decide +kernel
theorem S4_X1_30 : S4_D1.getD 30 [] = (expandE nS4_N nS4_E1).getD 30 [] := by decide +kernel
theorem S4_X1_31 : S4_D1.getD 31 [] = (expandE nS4_N nS4_E1).getD 31 [] := by decide +kernel
theorem S4_X1_32 : S4_D1.getD 32 [] = (expandE nS4_N nS4_E1).getD 32 [] := by decide +kernel
theorem S4_X1_33 : S4_D1.getD 33 [] = (expandE nS4_N nS4_E1).getD 33 [] := by decide +kernel
theorem S4_X1_34 : S4_D1.getD 34 [] = (expandE nS4_N nS4_E1).getD 34 [] := by decide +kernel

theorem S4_X1 : S4_D1 = expandE nS4_N nS4_E1 :=
  NBlk.eq_of_getD_rows (S4_Dl1.trans S4_Xl1.symm) fun a ha => by
    rw [S4_Dl1] at ha
    exact match a, ha with
      | 0, _ => S4_X1_0
      | 1, _ => S4_X1_1
      | 2, _ => S4_X1_2
      | 3, _ => S4_X1_3
      | 4, _ => S4_X1_4
      | 5, _ => S4_X1_5
      | 6, _ => S4_X1_6
      | 7, _ => S4_X1_7
      | 8, _ => S4_X1_8
      | 9, _ => S4_X1_9
      | 10, _ => S4_X1_10
      | 11, _ => S4_X1_11
      | 12, _ => S4_X1_12
      | 13, _ => S4_X1_13
      | 14, _ => S4_X1_14
      | 15, _ => S4_X1_15
      | 16, _ => S4_X1_16
      | 17, _ => S4_X1_17
      | 18, _ => S4_X1_18
      | 19, _ => S4_X1_19
      | 20, _ => S4_X1_20
      | 21, _ => S4_X1_21
      | 22, _ => S4_X1_22
      | 23, _ => S4_X1_23
      | 24, _ => S4_X1_24
      | 25, _ => S4_X1_25
      | 26, _ => S4_X1_26
      | 27, _ => S4_X1_27
      | 28, _ => S4_X1_28
      | 29, _ => S4_X1_29
      | 30, _ => S4_X1_30
      | 31, _ => S4_X1_31
      | 32, _ => S4_X1_32
      | 33, _ => S4_X1_33
      | 34, _ => S4_X1_34
      | _ + 35, h => absurd h (by omega)

theorem S4_Dl2 : S4_D2.length = 35 := by decide +kernel
theorem S4_Xl2 : (expandE nS4_N nS4_E2).length = 35 := by decide +kernel
theorem S4_X2_0 : S4_D2.getD 0 [] = (expandE nS4_N nS4_E2).getD 0 [] := by decide +kernel
theorem S4_X2_1 : S4_D2.getD 1 [] = (expandE nS4_N nS4_E2).getD 1 [] := by decide +kernel
theorem S4_X2_2 : S4_D2.getD 2 [] = (expandE nS4_N nS4_E2).getD 2 [] := by decide +kernel
theorem S4_X2_3 : S4_D2.getD 3 [] = (expandE nS4_N nS4_E2).getD 3 [] := by decide +kernel
theorem S4_X2_4 : S4_D2.getD 4 [] = (expandE nS4_N nS4_E2).getD 4 [] := by decide +kernel
theorem S4_X2_5 : S4_D2.getD 5 [] = (expandE nS4_N nS4_E2).getD 5 [] := by decide +kernel
theorem S4_X2_6 : S4_D2.getD 6 [] = (expandE nS4_N nS4_E2).getD 6 [] := by decide +kernel
theorem S4_X2_7 : S4_D2.getD 7 [] = (expandE nS4_N nS4_E2).getD 7 [] := by decide +kernel
theorem S4_X2_8 : S4_D2.getD 8 [] = (expandE nS4_N nS4_E2).getD 8 [] := by decide +kernel
theorem S4_X2_9 : S4_D2.getD 9 [] = (expandE nS4_N nS4_E2).getD 9 [] := by decide +kernel
theorem S4_X2_10 : S4_D2.getD 10 [] = (expandE nS4_N nS4_E2).getD 10 [] := by decide +kernel
theorem S4_X2_11 : S4_D2.getD 11 [] = (expandE nS4_N nS4_E2).getD 11 [] := by decide +kernel
theorem S4_X2_12 : S4_D2.getD 12 [] = (expandE nS4_N nS4_E2).getD 12 [] := by decide +kernel
theorem S4_X2_13 : S4_D2.getD 13 [] = (expandE nS4_N nS4_E2).getD 13 [] := by decide +kernel
theorem S4_X2_14 : S4_D2.getD 14 [] = (expandE nS4_N nS4_E2).getD 14 [] := by decide +kernel
theorem S4_X2_15 : S4_D2.getD 15 [] = (expandE nS4_N nS4_E2).getD 15 [] := by decide +kernel
theorem S4_X2_16 : S4_D2.getD 16 [] = (expandE nS4_N nS4_E2).getD 16 [] := by decide +kernel
theorem S4_X2_17 : S4_D2.getD 17 [] = (expandE nS4_N nS4_E2).getD 17 [] := by decide +kernel
theorem S4_X2_18 : S4_D2.getD 18 [] = (expandE nS4_N nS4_E2).getD 18 [] := by decide +kernel
theorem S4_X2_19 : S4_D2.getD 19 [] = (expandE nS4_N nS4_E2).getD 19 [] := by decide +kernel
theorem S4_X2_20 : S4_D2.getD 20 [] = (expandE nS4_N nS4_E2).getD 20 [] := by decide +kernel
theorem S4_X2_21 : S4_D2.getD 21 [] = (expandE nS4_N nS4_E2).getD 21 [] := by decide +kernel
theorem S4_X2_22 : S4_D2.getD 22 [] = (expandE nS4_N nS4_E2).getD 22 [] := by decide +kernel
theorem S4_X2_23 : S4_D2.getD 23 [] = (expandE nS4_N nS4_E2).getD 23 [] := by decide +kernel
theorem S4_X2_24 : S4_D2.getD 24 [] = (expandE nS4_N nS4_E2).getD 24 [] := by decide +kernel
theorem S4_X2_25 : S4_D2.getD 25 [] = (expandE nS4_N nS4_E2).getD 25 [] := by decide +kernel
theorem S4_X2_26 : S4_D2.getD 26 [] = (expandE nS4_N nS4_E2).getD 26 [] := by decide +kernel
theorem S4_X2_27 : S4_D2.getD 27 [] = (expandE nS4_N nS4_E2).getD 27 [] := by decide +kernel
theorem S4_X2_28 : S4_D2.getD 28 [] = (expandE nS4_N nS4_E2).getD 28 [] := by decide +kernel
theorem S4_X2_29 : S4_D2.getD 29 [] = (expandE nS4_N nS4_E2).getD 29 [] := by decide +kernel
theorem S4_X2_30 : S4_D2.getD 30 [] = (expandE nS4_N nS4_E2).getD 30 [] := by decide +kernel
theorem S4_X2_31 : S4_D2.getD 31 [] = (expandE nS4_N nS4_E2).getD 31 [] := by decide +kernel
theorem S4_X2_32 : S4_D2.getD 32 [] = (expandE nS4_N nS4_E2).getD 32 [] := by decide +kernel
theorem S4_X2_33 : S4_D2.getD 33 [] = (expandE nS4_N nS4_E2).getD 33 [] := by decide +kernel
theorem S4_X2_34 : S4_D2.getD 34 [] = (expandE nS4_N nS4_E2).getD 34 [] := by decide +kernel

theorem S4_X2 : S4_D2 = expandE nS4_N nS4_E2 :=
  NBlk.eq_of_getD_rows (S4_Dl2.trans S4_Xl2.symm) fun a ha => by
    rw [S4_Dl2] at ha
    exact match a, ha with
      | 0, _ => S4_X2_0
      | 1, _ => S4_X2_1
      | 2, _ => S4_X2_2
      | 3, _ => S4_X2_3
      | 4, _ => S4_X2_4
      | 5, _ => S4_X2_5
      | 6, _ => S4_X2_6
      | 7, _ => S4_X2_7
      | 8, _ => S4_X2_8
      | 9, _ => S4_X2_9
      | 10, _ => S4_X2_10
      | 11, _ => S4_X2_11
      | 12, _ => S4_X2_12
      | 13, _ => S4_X2_13
      | 14, _ => S4_X2_14
      | 15, _ => S4_X2_15
      | 16, _ => S4_X2_16
      | 17, _ => S4_X2_17
      | 18, _ => S4_X2_18
      | 19, _ => S4_X2_19
      | 20, _ => S4_X2_20
      | 21, _ => S4_X2_21
      | 22, _ => S4_X2_22
      | 23, _ => S4_X2_23
      | 24, _ => S4_X2_24
      | 25, _ => S4_X2_25
      | 26, _ => S4_X2_26
      | 27, _ => S4_X2_27
      | 28, _ => S4_X2_28
      | 29, _ => S4_X2_29
      | 30, _ => S4_X2_30
      | 31, _ => S4_X2_31
      | 32, _ => S4_X2_32
      | 33, _ => S4_X2_33
      | 34, _ => S4_X2_34
      | _ + 35, h => absurd h (by omega)

theorem nS4_Pl : (NBlk.ldl nS4_d nS4_l).length = 28 := by decide +kernel
theorem nS4_Pr : nS4_P.length = 28 := by decide +kernel
theorem nS4_P0 : (NBlk.ldl nS4_d nS4_l).getD 0 [] = nS4_P.getD 0 [] := by decide +kernel
theorem nS4_P1 : (NBlk.ldl nS4_d nS4_l).getD 1 [] = nS4_P.getD 1 [] := by decide +kernel
theorem nS4_P2 : (NBlk.ldl nS4_d nS4_l).getD 2 [] = nS4_P.getD 2 [] := by decide +kernel
theorem nS4_P3 : (NBlk.ldl nS4_d nS4_l).getD 3 [] = nS4_P.getD 3 [] := by decide +kernel
theorem nS4_P4 : (NBlk.ldl nS4_d nS4_l).getD 4 [] = nS4_P.getD 4 [] := by decide +kernel
theorem nS4_P5 : (NBlk.ldl nS4_d nS4_l).getD 5 [] = nS4_P.getD 5 [] := by decide +kernel
theorem nS4_P6 : (NBlk.ldl nS4_d nS4_l).getD 6 [] = nS4_P.getD 6 [] := by decide +kernel
theorem nS4_P7 : (NBlk.ldl nS4_d nS4_l).getD 7 [] = nS4_P.getD 7 [] := by decide +kernel
theorem nS4_P8 : (NBlk.ldl nS4_d nS4_l).getD 8 [] = nS4_P.getD 8 [] := by decide +kernel
theorem nS4_P9 : (NBlk.ldl nS4_d nS4_l).getD 9 [] = nS4_P.getD 9 [] := by decide +kernel
theorem nS4_P10 : (NBlk.ldl nS4_d nS4_l).getD 10 [] = nS4_P.getD 10 [] := by decide +kernel
theorem nS4_P11 : (NBlk.ldl nS4_d nS4_l).getD 11 [] = nS4_P.getD 11 [] := by decide +kernel
theorem nS4_P12 : (NBlk.ldl nS4_d nS4_l).getD 12 [] = nS4_P.getD 12 [] := by decide +kernel
theorem nS4_P13 : (NBlk.ldl nS4_d nS4_l).getD 13 [] = nS4_P.getD 13 [] := by decide +kernel
theorem nS4_P14 : (NBlk.ldl nS4_d nS4_l).getD 14 [] = nS4_P.getD 14 [] := by decide +kernel
theorem nS4_P15 : (NBlk.ldl nS4_d nS4_l).getD 15 [] = nS4_P.getD 15 [] := by decide +kernel
theorem nS4_P16 : (NBlk.ldl nS4_d nS4_l).getD 16 [] = nS4_P.getD 16 [] := by decide +kernel
theorem nS4_P17 : (NBlk.ldl nS4_d nS4_l).getD 17 [] = nS4_P.getD 17 [] := by decide +kernel
theorem nS4_P18 : (NBlk.ldl nS4_d nS4_l).getD 18 [] = nS4_P.getD 18 [] := by decide +kernel
theorem nS4_P19 : (NBlk.ldl nS4_d nS4_l).getD 19 [] = nS4_P.getD 19 [] := by decide +kernel
theorem nS4_P20 : (NBlk.ldl nS4_d nS4_l).getD 20 [] = nS4_P.getD 20 [] := by decide +kernel
theorem nS4_P21 : (NBlk.ldl nS4_d nS4_l).getD 21 [] = nS4_P.getD 21 [] := by decide +kernel
theorem nS4_P22 : (NBlk.ldl nS4_d nS4_l).getD 22 [] = nS4_P.getD 22 [] := by decide +kernel
theorem nS4_P23 : (NBlk.ldl nS4_d nS4_l).getD 23 [] = nS4_P.getD 23 [] := by decide +kernel
theorem nS4_P24 : (NBlk.ldl nS4_d nS4_l).getD 24 [] = nS4_P.getD 24 [] := by decide +kernel
theorem nS4_P25 : (NBlk.ldl nS4_d nS4_l).getD 25 [] = nS4_P.getD 25 [] := by decide +kernel
theorem nS4_P26 : (NBlk.ldl nS4_d nS4_l).getD 26 [] = nS4_P.getD 26 [] := by decide +kernel
theorem nS4_P27 : (NBlk.ldl nS4_d nS4_l).getD 27 [] = nS4_P.getD 27 [] := by decide +kernel

theorem nS4_hP : NBlk.ldl nS4_d nS4_l = nS4_P :=
  NBlk.eq_of_getD_rows (nS4_Pl.trans nS4_Pr.symm) fun a ha => by
    rw [nS4_Pl] at ha
    exact match a, ha with
      | 0, _ => nS4_P0
      | 1, _ => nS4_P1
      | 2, _ => nS4_P2
      | 3, _ => nS4_P3
      | 4, _ => nS4_P4
      | 5, _ => nS4_P5
      | 6, _ => nS4_P6
      | 7, _ => nS4_P7
      | 8, _ => nS4_P8
      | 9, _ => nS4_P9
      | 10, _ => nS4_P10
      | 11, _ => nS4_P11
      | 12, _ => nS4_P12
      | 13, _ => nS4_P13
      | 14, _ => nS4_P14
      | 15, _ => nS4_P15
      | 16, _ => nS4_P16
      | 17, _ => nS4_P17
      | 18, _ => nS4_P18
      | 19, _ => nS4_P19
      | 20, _ => nS4_P20
      | 21, _ => nS4_P21
      | 22, _ => nS4_P22
      | 23, _ => nS4_P23
      | 24, _ => nS4_P24
      | 25, _ => nS4_P25
      | 26, _ => nS4_P26
      | 27, _ => nS4_P27
      | _ + 28, h => absurd h (by omega)

theorem nS4_ok0 : okF 28 nS4_C0 = true := by decide +kernel
theorem nS4_lin0 : NBlk.matAdd nS4_P nS4_R0 = lin κ0 nS4_Es := by decide +kernel
theorem nS4_corner0 : CornerOK 3 28 nS4_Es κ0 nS4_C0 :=
  ⟨by decide +kernel, nS4_ok0, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nS4_C0 = NBlk.matAdd (NBlk.ldl nS4_d nS4_l) nS4_R0 from rfl, nS4_hP]
    exact nS4_lin0⟩
theorem nS4_ok1 : okF 28 nS4_C1 = true := by decide +kernel
theorem nS4_lin1 : NBlk.matAdd nS4_P nS4_R1 = lin κ1 nS4_Es := by decide +kernel
theorem nS4_corner1 : CornerOK 3 28 nS4_Es κ1 nS4_C1 :=
  ⟨by decide +kernel, nS4_ok1, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nS4_C1 = NBlk.matAdd (NBlk.ldl nS4_d nS4_l) nS4_R1 from rfl, nS4_hP]
    exact nS4_lin1⟩
theorem nS4_ok2 : okF 28 nS4_C2 = true := by decide +kernel
theorem nS4_lin2 : NBlk.matAdd nS4_P nS4_R2 = lin κ2 nS4_Es := by decide +kernel
theorem nS4_corner2 : CornerOK 3 28 nS4_Es κ2 nS4_C2 :=
  ⟨by decide +kernel, nS4_ok2, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nS4_C2 = NBlk.matAdd (NBlk.ldl nS4_d nS4_l) nS4_R2 from rfl, nS4_hP]
    exact nS4_lin2⟩
theorem nS4_ok3 : okF 28 nS4_C3 = true := by decide +kernel
theorem nS4_lin3 : NBlk.matAdd nS4_P nS4_R3 = lin κ3 nS4_Es := by decide +kernel
theorem nS4_corner3 : CornerOK 3 28 nS4_Es κ3 nS4_C3 :=
  ⟨by decide +kernel, nS4_ok3, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nS4_C3 = NBlk.matAdd (NBlk.ldl nS4_d nS4_l) nS4_R3 from rfl, nS4_hP]
    exact nS4_lin3⟩
/-- The checked `K`-block `S4`. -/
theorem nS4_kok : KOK 3 28 κs nS4_N nS4_Es [nS4_C0, nS4_C1, nS4_C2, nS4_C3] :=
  ⟨by decide +kernel, by decide +kernel, by decide +kernel,
    .cons nS4_corner0 (.cons nS4_corner1 (.cons nS4_corner2 (.cons nS4_corner3 .nil)))⟩
theorem nS4_mN : 35 ≤ nS4_N.length := by decide +kernel

end N5R1
