import N5R1.Data
import N5R1.Blocks
/-! N = 5, Coulomb (s = 1): SOS block `S7` (20 × 17).  The expanded component blocks are `Ñ·E_c·Ñᵀ`
(row by row), and the `K`-block with its corner witnesses (`KOK`; `ldl d l = P` row by row).

Generated by `lean/gen/emit_n5_s1.py` from `cert_n5_s1_short.json`
(sha256 66c5baa88a130761295e1a161f9fe35f8218c28e3defddc67ad22bcd5361e2e0).  Do not edit; regenerate. -/

namespace N5R1
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.Cert.Cert3 ThomsonN7.Cert.KB

-- large literals: elaboration budget only (no effect on what is checked)
set_option maxHeartbeats 0

theorem S7_Dl0 : S7_D0.length = 20 := by decide +kernel
theorem S7_Xl0 : (expandE nS7_N nS7_E0).length = 20 := by decide +kernel
theorem S7_X0_0 : S7_D0.getD 0 [] = (expandE nS7_N nS7_E0).getD 0 [] := by decide +kernel
theorem S7_X0_1 : S7_D0.getD 1 [] = (expandE nS7_N nS7_E0).getD 1 [] := by decide +kernel
theorem S7_X0_2 : S7_D0.getD 2 [] = (expandE nS7_N nS7_E0).getD 2 [] := by decide +kernel
theorem S7_X0_3 : S7_D0.getD 3 [] = (expandE nS7_N nS7_E0).getD 3 [] := by decide +kernel
theorem S7_X0_4 : S7_D0.getD 4 [] = (expandE nS7_N nS7_E0).getD 4 [] := by decide +kernel
theorem S7_X0_5 : S7_D0.getD 5 [] = (expandE nS7_N nS7_E0).getD 5 [] := by decide +kernel
theorem S7_X0_6 : S7_D0.getD 6 [] = (expandE nS7_N nS7_E0).getD 6 [] := by decide +kernel
theorem S7_X0_7 : S7_D0.getD 7 [] = (expandE nS7_N nS7_E0).getD 7 [] := by decide +kernel
theorem S7_X0_8 : S7_D0.getD 8 [] = (expandE nS7_N nS7_E0).getD 8 [] := by decide +kernel
theorem S7_X0_9 : S7_D0.getD 9 [] = (expandE nS7_N nS7_E0).getD 9 [] := by decide +kernel
theorem S7_X0_10 : S7_D0.getD 10 [] = (expandE nS7_N nS7_E0).getD 10 [] := by decide +kernel
theorem S7_X0_11 : S7_D0.getD 11 [] = (expandE nS7_N nS7_E0).getD 11 [] := by decide +kernel
theorem S7_X0_12 : S7_D0.getD 12 [] = (expandE nS7_N nS7_E0).getD 12 [] := by decide +kernel
theorem S7_X0_13 : S7_D0.getD 13 [] = (expandE nS7_N nS7_E0).getD 13 [] := by decide +kernel
theorem S7_X0_14 : S7_D0.getD 14 [] = (expandE nS7_N nS7_E0).getD 14 [] := by decide +kernel
theorem S7_X0_15 : S7_D0.getD 15 [] = (expandE nS7_N nS7_E0).getD 15 [] := by decide +kernel
theorem S7_X0_16 : S7_D0.getD 16 [] = (expandE nS7_N nS7_E0).getD 16 [] := by decide +kernel
theorem S7_X0_17 : S7_D0.getD 17 [] = (expandE nS7_N nS7_E0).getD 17 [] := by decide +kernel
theorem S7_X0_18 : S7_D0.getD 18 [] = (expandE nS7_N nS7_E0).getD 18 [] := by decide +kernel
theorem S7_X0_19 : S7_D0.getD 19 [] = (expandE nS7_N nS7_E0).getD 19 [] := by decide +kernel

theorem S7_X0 : S7_D0 = expandE nS7_N nS7_E0 :=
  NBlk.eq_of_getD_rows (S7_Dl0.trans S7_Xl0.symm) fun a ha => by
    rw [S7_Dl0] at ha
    exact match a, ha with
      | 0, _ => S7_X0_0
      | 1, _ => S7_X0_1
      | 2, _ => S7_X0_2
      | 3, _ => S7_X0_3
      | 4, _ => S7_X0_4
      | 5, _ => S7_X0_5
      | 6, _ => S7_X0_6
      | 7, _ => S7_X0_7
      | 8, _ => S7_X0_8
      | 9, _ => S7_X0_9
      | 10, _ => S7_X0_10
      | 11, _ => S7_X0_11
      | 12, _ => S7_X0_12
      | 13, _ => S7_X0_13
      | 14, _ => S7_X0_14
      | 15, _ => S7_X0_15
      | 16, _ => S7_X0_16
      | 17, _ => S7_X0_17
      | 18, _ => S7_X0_18
      | 19, _ => S7_X0_19
      | _ + 20, h => absurd h (by omega)

theorem S7_Dl1 : S7_D1.length = 20 := by decide +kernel
theorem S7_Xl1 : (expandE nS7_N nS7_E1).length = 20 := by decide +kernel
theorem S7_X1_0 : S7_D1.getD 0 [] = (expandE nS7_N nS7_E1).getD 0 [] := by decide +kernel
theorem S7_X1_1 : S7_D1.getD 1 [] = (expandE nS7_N nS7_E1).getD 1 [] := by decide +kernel
theorem S7_X1_2 : S7_D1.getD 2 [] = (expandE nS7_N nS7_E1).getD 2 [] := by decide +kernel
theorem S7_X1_3 : S7_D1.getD 3 [] = (expandE nS7_N nS7_E1).getD 3 [] := by decide +kernel
theorem S7_X1_4 : S7_D1.getD 4 [] = (expandE nS7_N nS7_E1).getD 4 [] := by decide +kernel
theorem S7_X1_5 : S7_D1.getD 5 [] = (expandE nS7_N nS7_E1).getD 5 [] := by decide +kernel
theorem S7_X1_6 : S7_D1.getD 6 [] = (expandE nS7_N nS7_E1).getD 6 [] := by decide +kernel
theorem S7_X1_7 : S7_D1.getD 7 [] = (expandE nS7_N nS7_E1).getD 7 [] := by decide +kernel
theorem S7_X1_8 : S7_D1.getD 8 [] = (expandE nS7_N nS7_E1).getD 8 [] := by decide +kernel
theorem S7_X1_9 : S7_D1.getD 9 [] = (expandE nS7_N nS7_E1).getD 9 [] := by decide +kernel
theorem S7_X1_10 : S7_D1.getD 10 [] = (expandE nS7_N nS7_E1).getD 10 [] := by decide +kernel
theorem S7_X1_11 : S7_D1.getD 11 [] = (expandE nS7_N nS7_E1).getD 11 [] := by decide +kernel
theorem S7_X1_12 : S7_D1.getD 12 [] = (expandE nS7_N nS7_E1).getD 12 [] := by decide +kernel
theorem S7_X1_13 : S7_D1.getD 13 [] = (expandE nS7_N nS7_E1).getD 13 [] := by decide +kernel
theorem S7_X1_14 : S7_D1.getD 14 [] = (expandE nS7_N nS7_E1).getD 14 [] := by decide +kernel
theorem S7_X1_15 : S7_D1.getD 15 [] = (expandE nS7_N nS7_E1).getD 15 [] := by decide +kernel
theorem S7_X1_16 : S7_D1.getD 16 [] = (expandE nS7_N nS7_E1).getD 16 [] := by decide +kernel
theorem S7_X1_17 : S7_D1.getD 17 [] = (expandE nS7_N nS7_E1).getD 17 [] := by decide +kernel
theorem S7_X1_18 : S7_D1.getD 18 [] = (expandE nS7_N nS7_E1).getD 18 [] := by decide +kernel
theorem S7_X1_19 : S7_D1.getD 19 [] = (expandE nS7_N nS7_E1).getD 19 [] := by decide +kernel

theorem S7_X1 : S7_D1 = expandE nS7_N nS7_E1 :=
  NBlk.eq_of_getD_rows (S7_Dl1.trans S7_Xl1.symm) fun a ha => by
    rw [S7_Dl1] at ha
    exact match a, ha with
      | 0, _ => S7_X1_0
      | 1, _ => S7_X1_1
      | 2, _ => S7_X1_2
      | 3, _ => S7_X1_3
      | 4, _ => S7_X1_4
      | 5, _ => S7_X1_5
      | 6, _ => S7_X1_6
      | 7, _ => S7_X1_7
      | 8, _ => S7_X1_8
      | 9, _ => S7_X1_9
      | 10, _ => S7_X1_10
      | 11, _ => S7_X1_11
      | 12, _ => S7_X1_12
      | 13, _ => S7_X1_13
      | 14, _ => S7_X1_14
      | 15, _ => S7_X1_15
      | 16, _ => S7_X1_16
      | 17, _ => S7_X1_17
      | 18, _ => S7_X1_18
      | 19, _ => S7_X1_19
      | _ + 20, h => absurd h (by omega)

theorem S7_Dl2 : S7_D2.length = 20 := by decide +kernel
theorem S7_Xl2 : (expandE nS7_N nS7_E2).length = 20 := by decide +kernel
theorem S7_X2_0 : S7_D2.getD 0 [] = (expandE nS7_N nS7_E2).getD 0 [] := by decide +kernel
theorem S7_X2_1 : S7_D2.getD 1 [] = (expandE nS7_N nS7_E2).getD 1 [] := by decide +kernel
theorem S7_X2_2 : S7_D2.getD 2 [] = (expandE nS7_N nS7_E2).getD 2 [] := by decide +kernel
theorem S7_X2_3 : S7_D2.getD 3 [] = (expandE nS7_N nS7_E2).getD 3 [] := by decide +kernel
theorem S7_X2_4 : S7_D2.getD 4 [] = (expandE nS7_N nS7_E2).getD 4 [] := by decide +kernel
theorem S7_X2_5 : S7_D2.getD 5 [] = (expandE nS7_N nS7_E2).getD 5 [] := by decide +kernel
theorem S7_X2_6 : S7_D2.getD 6 [] = (expandE nS7_N nS7_E2).getD 6 [] := by decide +kernel
theorem S7_X2_7 : S7_D2.getD 7 [] = (expandE nS7_N nS7_E2).getD 7 [] := by decide +kernel
theorem S7_X2_8 : S7_D2.getD 8 [] = (expandE nS7_N nS7_E2).getD 8 [] := by decide +kernel
theorem S7_X2_9 : S7_D2.getD 9 [] = (expandE nS7_N nS7_E2).getD 9 [] := by decide +kernel
theorem S7_X2_10 : S7_D2.getD 10 [] = (expandE nS7_N nS7_E2).getD 10 [] := by decide +kernel
theorem S7_X2_11 : S7_D2.getD 11 [] = (expandE nS7_N nS7_E2).getD 11 [] := by decide +kernel
theorem S7_X2_12 : S7_D2.getD 12 [] = (expandE nS7_N nS7_E2).getD 12 [] := by decide +kernel
theorem S7_X2_13 : S7_D2.getD 13 [] = (expandE nS7_N nS7_E2).getD 13 [] := by decide +kernel
theorem S7_X2_14 : S7_D2.getD 14 [] = (expandE nS7_N nS7_E2).getD 14 [] := by decide +kernel
theorem S7_X2_15 : S7_D2.getD 15 [] = (expandE nS7_N nS7_E2).getD 15 [] := by decide +kernel
theorem S7_X2_16 : S7_D2.getD 16 [] = (expandE nS7_N nS7_E2).getD 16 [] := by decide +kernel
theorem S7_X2_17 : S7_D2.getD 17 [] = (expandE nS7_N nS7_E2).getD 17 [] := by decide +kernel
theorem S7_X2_18 : S7_D2.getD 18 [] = (expandE nS7_N nS7_E2).getD 18 [] := by decide +kernel
theorem S7_X2_19 : S7_D2.getD 19 [] = (expandE nS7_N nS7_E2).getD 19 [] := by decide +kernel

theorem S7_X2 : S7_D2 = expandE nS7_N nS7_E2 :=
  NBlk.eq_of_getD_rows (S7_Dl2.trans S7_Xl2.symm) fun a ha => by
    rw [S7_Dl2] at ha
    exact match a, ha with
      | 0, _ => S7_X2_0
      | 1, _ => S7_X2_1
      | 2, _ => S7_X2_2
      | 3, _ => S7_X2_3
      | 4, _ => S7_X2_4
      | 5, _ => S7_X2_5
      | 6, _ => S7_X2_6
      | 7, _ => S7_X2_7
      | 8, _ => S7_X2_8
      | 9, _ => S7_X2_9
      | 10, _ => S7_X2_10
      | 11, _ => S7_X2_11
      | 12, _ => S7_X2_12
      | 13, _ => S7_X2_13
      | 14, _ => S7_X2_14
      | 15, _ => S7_X2_15
      | 16, _ => S7_X2_16
      | 17, _ => S7_X2_17
      | 18, _ => S7_X2_18
      | 19, _ => S7_X2_19
      | _ + 20, h => absurd h (by omega)

theorem nS7_Pl : (NBlk.ldl nS7_d nS7_l).length = 17 := by decide +kernel
theorem nS7_Pr : nS7_P.length = 17 := by decide +kernel
theorem nS7_P0 : (NBlk.ldl nS7_d nS7_l).getD 0 [] = nS7_P.getD 0 [] := by decide +kernel
theorem nS7_P1 : (NBlk.ldl nS7_d nS7_l).getD 1 [] = nS7_P.getD 1 [] := by decide +kernel
theorem nS7_P2 : (NBlk.ldl nS7_d nS7_l).getD 2 [] = nS7_P.getD 2 [] := by decide +kernel
theorem nS7_P3 : (NBlk.ldl nS7_d nS7_l).getD 3 [] = nS7_P.getD 3 [] := by decide +kernel
theorem nS7_P4 : (NBlk.ldl nS7_d nS7_l).getD 4 [] = nS7_P.getD 4 [] := by decide +kernel
theorem nS7_P5 : (NBlk.ldl nS7_d nS7_l).getD 5 [] = nS7_P.getD 5 [] := by decide +kernel
theorem nS7_P6 : (NBlk.ldl nS7_d nS7_l).getD 6 [] = nS7_P.getD 6 [] := by decide +kernel
theorem nS7_P7 : (NBlk.ldl nS7_d nS7_l).getD 7 [] = nS7_P.getD 7 [] := by decide +kernel
theorem nS7_P8 : (NBlk.ldl nS7_d nS7_l).getD 8 [] = nS7_P.getD 8 [] := by decide +kernel
theorem nS7_P9 : (NBlk.ldl nS7_d nS7_l).getD 9 [] = nS7_P.getD 9 [] := by decide +kernel
theorem nS7_P10 : (NBlk.ldl nS7_d nS7_l).getD 10 [] = nS7_P.getD 10 [] := by decide +kernel
theorem nS7_P11 : (NBlk.ldl nS7_d nS7_l).getD 11 [] = nS7_P.getD 11 [] := by decide +kernel
theorem nS7_P12 : (NBlk.ldl nS7_d nS7_l).getD 12 [] = nS7_P.getD 12 [] := by decide +kernel
theorem nS7_P13 : (NBlk.ldl nS7_d nS7_l).getD 13 [] = nS7_P.getD 13 [] := by decide +kernel
theorem nS7_P14 : (NBlk.ldl nS7_d nS7_l).getD 14 [] = nS7_P.getD 14 [] := by decide +kernel
theorem nS7_P15 : (NBlk.ldl nS7_d nS7_l).getD 15 [] = nS7_P.getD 15 [] := by decide +kernel
theorem nS7_P16 : (NBlk.ldl nS7_d nS7_l).getD 16 [] = nS7_P.getD 16 [] := by decide +kernel

theorem nS7_hP : NBlk.ldl nS7_d nS7_l = nS7_P :=
  NBlk.eq_of_getD_rows (nS7_Pl.trans nS7_Pr.symm) fun a ha => by
    rw [nS7_Pl] at ha
    exact match a, ha with
      | 0, _ => nS7_P0
      | 1, _ => nS7_P1
      | 2, _ => nS7_P2
      | 3, _ => nS7_P3
      | 4, _ => nS7_P4
      | 5, _ => nS7_P5
      | 6, _ => nS7_P6
      | 7, _ => nS7_P7
      | 8, _ => nS7_P8
      | 9, _ => nS7_P9
      | 10, _ => nS7_P10
      | 11, _ => nS7_P11
      | 12, _ => nS7_P12
      | 13, _ => nS7_P13
      | 14, _ => nS7_P14
      | 15, _ => nS7_P15
      | 16, _ => nS7_P16
      | _ + 17, h => absurd h (by omega)

theorem nS7_ok0 : okF 17 nS7_C0 = true := by decide +kernel
theorem nS7_lin0 : NBlk.matAdd nS7_P nS7_R0 = lin κ0 nS7_Es := by decide +kernel
theorem nS7_corner0 : CornerOK 3 17 nS7_Es κ0 nS7_C0 :=
  ⟨by decide +kernel, nS7_ok0, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nS7_C0 = NBlk.matAdd (NBlk.ldl nS7_d nS7_l) nS7_R0 from rfl, nS7_hP]
    exact nS7_lin0⟩
theorem nS7_ok1 : okF 17 nS7_C1 = true := by decide +kernel
theorem nS7_lin1 : NBlk.matAdd nS7_P nS7_R1 = lin κ1 nS7_Es := by decide +kernel
theorem nS7_corner1 : CornerOK 3 17 nS7_Es κ1 nS7_C1 :=
  ⟨by decide +kernel, nS7_ok1, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nS7_C1 = NBlk.matAdd (NBlk.ldl nS7_d nS7_l) nS7_R1 from rfl, nS7_hP]
    exact nS7_lin1⟩
theorem nS7_ok2 : okF 17 nS7_C2 = true := by decide +kernel
theorem nS7_lin2 : NBlk.matAdd nS7_P nS7_R2 = lin κ2 nS7_Es := by decide +kernel
theorem nS7_corner2 : CornerOK 3 17 nS7_Es κ2 nS7_C2 :=
  ⟨by decide +kernel, nS7_ok2, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nS7_C2 = NBlk.matAdd (NBlk.ldl nS7_d nS7_l) nS7_R2 from rfl, nS7_hP]
    exact nS7_lin2⟩
theorem nS7_ok3 : okF 17 nS7_C3 = true := by decide +kernel
theorem nS7_lin3 : NBlk.matAdd nS7_P nS7_R3 = lin κ3 nS7_Es := by decide +kernel
theorem nS7_corner3 : CornerOK 3 17 nS7_Es κ3 nS7_C3 :=
  ⟨by decide +kernel, nS7_ok3, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nS7_C3 = NBlk.matAdd (NBlk.ldl nS7_d nS7_l) nS7_R3 from rfl, nS7_hP]
    exact nS7_lin3⟩
/-- The checked `K`-block `S7`. -/
theorem nS7_kok : KOK 3 17 κs nS7_N nS7_Es [nS7_C0, nS7_C1, nS7_C2, nS7_C3] :=
  ⟨by decide +kernel, by decide +kernel, by decide +kernel,
    .cons nS7_corner0 (.cons nS7_corner1 (.cons nS7_corner2 (.cons nS7_corner3 .nil)))⟩
theorem nS7_mN : 20 ≤ nS7_N.length := by decide +kernel

end N5R1
