import N5R1.Data
import N5R1.Blocks
/-! N = 5, Coulomb (s = 1): SOS block `S0` (56 × 49), part 1 of 2.  The expanded component blocks (`1`, `√2`) are `Ñ·E_c·Ñᵀ` (row by row).


Generated by `lean/gen/emit_n5_s1.py` from `cert_n5_s1_short.json`
(sha256 66c5baa88a130761295e1a161f9fe35f8218c28e3defddc67ad22bcd5361e2e0).  Do not edit; regenerate. -/

namespace N5R1
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.Cert.Cert3 ThomsonN7.Cert.KB

-- large literals: elaboration budget only (no effect on what is checked)
set_option maxHeartbeats 0

theorem S0_Dl0 : S0_D0.length = 56 := by decide +kernel
theorem S0_Xl0 : (expandE nS0_N nS0_E0).length = 56 := by decide +kernel
theorem S0_X0_0 : S0_D0.getD 0 [] = (expandE nS0_N nS0_E0).getD 0 [] := by decide +kernel
theorem S0_X0_1 : S0_D0.getD 1 [] = (expandE nS0_N nS0_E0).getD 1 [] := by decide +kernel
theorem S0_X0_2 : S0_D0.getD 2 [] = (expandE nS0_N nS0_E0).getD 2 [] := by decide +kernel
theorem S0_X0_3 : S0_D0.getD 3 [] = (expandE nS0_N nS0_E0).getD 3 [] := by decide +kernel
theorem S0_X0_4 : S0_D0.getD 4 [] = (expandE nS0_N nS0_E0).getD 4 [] := by decide +kernel
theorem S0_X0_5 : S0_D0.getD 5 [] = (expandE nS0_N nS0_E0).getD 5 [] := by decide +kernel
theorem S0_X0_6 : S0_D0.getD 6 [] = (expandE nS0_N nS0_E0).getD 6 [] := by decide +kernel
theorem S0_X0_7 : S0_D0.getD 7 [] = (expandE nS0_N nS0_E0).getD 7 [] := by decide +kernel
theorem S0_X0_8 : S0_D0.getD 8 [] = (expandE nS0_N nS0_E0).getD 8 [] := by decide +kernel
theorem S0_X0_9 : S0_D0.getD 9 [] = (expandE nS0_N nS0_E0).getD 9 [] := by decide +kernel
theorem S0_X0_10 : S0_D0.getD 10 [] = (expandE nS0_N nS0_E0).getD 10 [] := by decide +kernel
theorem S0_X0_11 : S0_D0.getD 11 [] = (expandE nS0_N nS0_E0).getD 11 [] := by decide +kernel
theorem S0_X0_12 : S0_D0.getD 12 [] = (expandE nS0_N nS0_E0).getD 12 [] := by decide +kernel
theorem S0_X0_13 : S0_D0.getD 13 [] = (expandE nS0_N nS0_E0).getD 13 [] := by decide +kernel
theorem S0_X0_14 : S0_D0.getD 14 [] = (expandE nS0_N nS0_E0).getD 14 [] := by decide +kernel
theorem S0_X0_15 : S0_D0.getD 15 [] = (expandE nS0_N nS0_E0).getD 15 [] := by decide +kernel
theorem S0_X0_16 : S0_D0.getD 16 [] = (expandE nS0_N nS0_E0).getD 16 [] := by decide +kernel
theorem S0_X0_17 : S0_D0.getD 17 [] = (expandE nS0_N nS0_E0).getD 17 [] := by decide +kernel
theorem S0_X0_18 : S0_D0.getD 18 [] = (expandE nS0_N nS0_E0).getD 18 [] := by decide +kernel
theorem S0_X0_19 : S0_D0.getD 19 [] = (expandE nS0_N nS0_E0).getD 19 [] := by decide +kernel
theorem S0_X0_20 : S0_D0.getD 20 [] = (expandE nS0_N nS0_E0).getD 20 [] := by decide +kernel
theorem S0_X0_21 : S0_D0.getD 21 [] = (expandE nS0_N nS0_E0).getD 21 [] := by decide +kernel
theorem S0_X0_22 : S0_D0.getD 22 [] = (expandE nS0_N nS0_E0).getD 22 [] := by decide +kernel
theorem S0_X0_23 : S0_D0.getD 23 [] = (expandE nS0_N nS0_E0).getD 23 [] := by decide +kernel
theorem S0_X0_24 : S0_D0.getD 24 [] = (expandE nS0_N nS0_E0).getD 24 [] := by decide +kernel
theorem S0_X0_25 : S0_D0.getD 25 [] = (expandE nS0_N nS0_E0).getD 25 [] := by decide +kernel
theorem S0_X0_26 : S0_D0.getD 26 [] = (expandE nS0_N nS0_E0).getD 26 [] := by decide +kernel
theorem S0_X0_27 : S0_D0.getD 27 [] = (expandE nS0_N nS0_E0).getD 27 [] := by decide +kernel
theorem S0_X0_28 : S0_D0.getD 28 [] = (expandE nS0_N nS0_E0).getD 28 [] := by decide +kernel
theorem S0_X0_29 : S0_D0.getD 29 [] = (expandE nS0_N nS0_E0).getD 29 [] := by decide +kernel
theorem S0_X0_30 : S0_D0.getD 30 [] = (expandE nS0_N nS0_E0).getD 30 [] := by decide +kernel
theorem S0_X0_31 : S0_D0.getD 31 [] = (expandE nS0_N nS0_E0).getD 31 [] := by decide +kernel
theorem S0_X0_32 : S0_D0.getD 32 [] = (expandE nS0_N nS0_E0).getD 32 [] := by decide +kernel
theorem S0_X0_33 : S0_D0.getD 33 [] = (expandE nS0_N nS0_E0).getD 33 [] := by decide +kernel
theorem S0_X0_34 : S0_D0.getD 34 [] = (expandE nS0_N nS0_E0).getD 34 [] := by decide +kernel
theorem S0_X0_35 : S0_D0.getD 35 [] = (expandE nS0_N nS0_E0).getD 35 [] := by decide +kernel
theorem S0_X0_36 : S0_D0.getD 36 [] = (expandE nS0_N nS0_E0).getD 36 [] := by decide +kernel
theorem S0_X0_37 : S0_D0.getD 37 [] = (expandE nS0_N nS0_E0).getD 37 [] := by decide +kernel
theorem S0_X0_38 : S0_D0.getD 38 [] = (expandE nS0_N nS0_E0).getD 38 [] := by decide +kernel
theorem S0_X0_39 : S0_D0.getD 39 [] = (expandE nS0_N nS0_E0).getD 39 [] := by decide +kernel
theorem S0_X0_40 : S0_D0.getD 40 [] = (expandE nS0_N nS0_E0).getD 40 [] := by decide +kernel
theorem S0_X0_41 : S0_D0.getD 41 [] = (expandE nS0_N nS0_E0).getD 41 [] := by decide +kernel
theorem S0_X0_42 : S0_D0.getD 42 [] = (expandE nS0_N nS0_E0).getD 42 [] := by decide +kernel
theorem S0_X0_43 : S0_D0.getD 43 [] = (expandE nS0_N nS0_E0).getD 43 [] := by decide +kernel
theorem S0_X0_44 : S0_D0.getD 44 [] = (expandE nS0_N nS0_E0).getD 44 [] := by decide +kernel
theorem S0_X0_45 : S0_D0.getD 45 [] = (expandE nS0_N nS0_E0).getD 45 [] := by decide +kernel
theorem S0_X0_46 : S0_D0.getD 46 [] = (expandE nS0_N nS0_E0).getD 46 [] := by decide +kernel
theorem S0_X0_47 : S0_D0.getD 47 [] = (expandE nS0_N nS0_E0).getD 47 [] := by decide +kernel
theorem S0_X0_48 : S0_D0.getD 48 [] = (expandE nS0_N nS0_E0).getD 48 [] := by decide +kernel
theorem S0_X0_49 : S0_D0.getD 49 [] = (expandE nS0_N nS0_E0).getD 49 [] := by decide +kernel
theorem S0_X0_50 : S0_D0.getD 50 [] = (expandE nS0_N nS0_E0).getD 50 [] := by decide +kernel
theorem S0_X0_51 : S0_D0.getD 51 [] = (expandE nS0_N nS0_E0).getD 51 [] := by decide +kernel
theorem S0_X0_52 : S0_D0.getD 52 [] = (expandE nS0_N nS0_E0).getD 52 [] := by decide +kernel
theorem S0_X0_53 : S0_D0.getD 53 [] = (expandE nS0_N nS0_E0).getD 53 [] := by decide +kernel
theorem S0_X0_54 : S0_D0.getD 54 [] = (expandE nS0_N nS0_E0).getD 54 [] := by decide +kernel
theorem S0_X0_55 : S0_D0.getD 55 [] = (expandE nS0_N nS0_E0).getD 55 [] := by decide +kernel

theorem S0_X0 : S0_D0 = expandE nS0_N nS0_E0 :=
  NBlk.eq_of_getD_rows (S0_Dl0.trans S0_Xl0.symm) fun a ha => by
    rw [S0_Dl0] at ha
    exact match a, ha with
      | 0, _ => S0_X0_0
      | 1, _ => S0_X0_1
      | 2, _ => S0_X0_2
      | 3, _ => S0_X0_3
      | 4, _ => S0_X0_4
      | 5, _ => S0_X0_5
      | 6, _ => S0_X0_6
      | 7, _ => S0_X0_7
      | 8, _ => S0_X0_8
      | 9, _ => S0_X0_9
      | 10, _ => S0_X0_10
      | 11, _ => S0_X0_11
      | 12, _ => S0_X0_12
      | 13, _ => S0_X0_13
      | 14, _ => S0_X0_14
      | 15, _ => S0_X0_15
      | 16, _ => S0_X0_16
      | 17, _ => S0_X0_17
      | 18, _ => S0_X0_18
      | 19, _ => S0_X0_19
      | 20, _ => S0_X0_20
      | 21, _ => S0_X0_21
      | 22, _ => S0_X0_22
      | 23, _ => S0_X0_23
      | 24, _ => S0_X0_24
      | 25, _ => S0_X0_25
      | 26, _ => S0_X0_26
      | 27, _ => S0_X0_27
      | 28, _ => S0_X0_28
      | 29, _ => S0_X0_29
      | 30, _ => S0_X0_30
      | 31, _ => S0_X0_31
      | 32, _ => S0_X0_32
      | 33, _ => S0_X0_33
      | 34, _ => S0_X0_34
      | 35, _ => S0_X0_35
      | 36, _ => S0_X0_36
      | 37, _ => S0_X0_37
      | 38, _ => S0_X0_38
      | 39, _ => S0_X0_39
      | 40, _ => S0_X0_40
      | 41, _ => S0_X0_41
      | 42, _ => S0_X0_42
      | 43, _ => S0_X0_43
      | 44, _ => S0_X0_44
      | 45, _ => S0_X0_45
      | 46, _ => S0_X0_46
      | 47, _ => S0_X0_47
      | 48, _ => S0_X0_48
      | 49, _ => S0_X0_49
      | 50, _ => S0_X0_50
      | 51, _ => S0_X0_51
      | 52, _ => S0_X0_52
      | 53, _ => S0_X0_53
      | 54, _ => S0_X0_54
      | 55, _ => S0_X0_55
      | _ + 56, h => absurd h (by omega)

theorem S0_Dl1 : S0_D1.length = 56 := by decide +kernel
theorem S0_Xl1 : (expandE nS0_N nS0_E1).length = 56 := by decide +kernel
theorem S0_X1_0 : S0_D1.getD 0 [] = (expandE nS0_N nS0_E1).getD 0 [] := by decide +kernel
theorem S0_X1_1 : S0_D1.getD 1 [] = (expandE nS0_N nS0_E1).getD 1 [] := by decide +kernel
theorem S0_X1_2 : S0_D1.getD 2 [] = (expandE nS0_N nS0_E1).getD 2 [] := by decide +kernel
theorem S0_X1_3 : S0_D1.getD 3 [] = (expandE nS0_N nS0_E1).getD 3 [] := by decide +kernel
theorem S0_X1_4 : S0_D1.getD 4 [] = (expandE nS0_N nS0_E1).getD 4 [] := by decide +kernel
theorem S0_X1_5 : S0_D1.getD 5 [] = (expandE nS0_N nS0_E1).getD 5 [] := by decide +kernel
theorem S0_X1_6 : S0_D1.getD 6 [] = (expandE nS0_N nS0_E1).getD 6 [] := by decide +kernel
theorem S0_X1_7 : S0_D1.getD 7 [] = (expandE nS0_N nS0_E1).getD 7 [] := by decide +kernel
theorem S0_X1_8 : S0_D1.getD 8 [] = (expandE nS0_N nS0_E1).getD 8 [] := by decide +kernel
theorem S0_X1_9 : S0_D1.getD 9 [] = (expandE nS0_N nS0_E1).getD 9 [] := by decide +kernel
theorem S0_X1_10 : S0_D1.getD 10 [] = (expandE nS0_N nS0_E1).getD 10 [] := by decide +kernel
theorem S0_X1_11 : S0_D1.getD 11 [] = (expandE nS0_N nS0_E1).getD 11 [] := by decide +kernel
theorem S0_X1_12 : S0_D1.getD 12 [] = (expandE nS0_N nS0_E1).getD 12 [] := by decide +kernel
theorem S0_X1_13 : S0_D1.getD 13 [] = (expandE nS0_N nS0_E1).getD 13 [] := by decide +kernel
theorem S0_X1_14 : S0_D1.getD 14 [] = (expandE nS0_N nS0_E1).getD 14 [] := by decide +kernel
theorem S0_X1_15 : S0_D1.getD 15 [] = (expandE nS0_N nS0_E1).getD 15 [] := by decide +kernel
theorem S0_X1_16 : S0_D1.getD 16 [] = (expandE nS0_N nS0_E1).getD 16 [] := by decide +kernel
theorem S0_X1_17 : S0_D1.getD 17 [] = (expandE nS0_N nS0_E1).getD 17 [] := by decide +kernel
theorem S0_X1_18 : S0_D1.getD 18 [] = (expandE nS0_N nS0_E1).getD 18 [] := by decide +kernel
theorem S0_X1_19 : S0_D1.getD 19 [] = (expandE nS0_N nS0_E1).getD 19 [] := by decide +kernel
theorem S0_X1_20 : S0_D1.getD 20 [] = (expandE nS0_N nS0_E1).getD 20 [] := by decide +kernel
theorem S0_X1_21 : S0_D1.getD 21 [] = (expandE nS0_N nS0_E1).getD 21 [] := by decide +kernel
theorem S0_X1_22 : S0_D1.getD 22 [] = (expandE nS0_N nS0_E1).getD 22 [] := by decide +kernel
theorem S0_X1_23 : S0_D1.getD 23 [] = (expandE nS0_N nS0_E1).getD 23 [] := by decide +kernel
theorem S0_X1_24 : S0_D1.getD 24 [] = (expandE nS0_N nS0_E1).getD 24 [] := by decide +kernel
theorem S0_X1_25 : S0_D1.getD 25 [] = (expandE nS0_N nS0_E1).getD 25 [] := by decide +kernel
theorem S0_X1_26 : S0_D1.getD 26 [] = (expandE nS0_N nS0_E1).getD 26 [] := by decide +kernel
theorem S0_X1_27 : S0_D1.getD 27 [] = (expandE nS0_N nS0_E1).getD 27 [] := by decide +kernel
theorem S0_X1_28 : S0_D1.getD 28 [] = (expandE nS0_N nS0_E1).getD 28 [] := by decide +kernel
theorem S0_X1_29 : S0_D1.getD 29 [] = (expandE nS0_N nS0_E1).getD 29 [] := by decide +kernel
theorem S0_X1_30 : S0_D1.getD 30 [] = (expandE nS0_N nS0_E1).getD 30 [] := by decide +kernel
theorem S0_X1_31 : S0_D1.getD 31 [] = (expandE nS0_N nS0_E1).getD 31 [] := by decide +kernel
theorem S0_X1_32 : S0_D1.getD 32 [] = (expandE nS0_N nS0_E1).getD 32 [] := by decide +kernel
theorem S0_X1_33 : S0_D1.getD 33 [] = (expandE nS0_N nS0_E1).getD 33 [] := by decide +kernel
theorem S0_X1_34 : S0_D1.getD 34 [] = (expandE nS0_N nS0_E1).getD 34 [] := by decide +kernel
theorem S0_X1_35 : S0_D1.getD 35 [] = (expandE nS0_N nS0_E1).getD 35 [] := by decide +kernel
theorem S0_X1_36 : S0_D1.getD 36 [] = (expandE nS0_N nS0_E1).getD 36 [] := by decide +kernel
theorem S0_X1_37 : S0_D1.getD 37 [] = (expandE nS0_N nS0_E1).getD 37 [] := by decide +kernel
theorem S0_X1_38 : S0_D1.getD 38 [] = (expandE nS0_N nS0_E1).getD 38 [] := by decide +kernel
theorem S0_X1_39 : S0_D1.getD 39 [] = (expandE nS0_N nS0_E1).getD 39 [] := by decide +kernel
theorem S0_X1_40 : S0_D1.getD 40 [] = (expandE nS0_N nS0_E1).getD 40 [] := by decide +kernel
theorem S0_X1_41 : S0_D1.getD 41 [] = (expandE nS0_N nS0_E1).getD 41 [] := by decide +kernel
theorem S0_X1_42 : S0_D1.getD 42 [] = (expandE nS0_N nS0_E1).getD 42 [] := by decide +kernel
theorem S0_X1_43 : S0_D1.getD 43 [] = (expandE nS0_N nS0_E1).getD 43 [] := by decide +kernel
theorem S0_X1_44 : S0_D1.getD 44 [] = (expandE nS0_N nS0_E1).getD 44 [] := by decide +kernel
theorem S0_X1_45 : S0_D1.getD 45 [] = (expandE nS0_N nS0_E1).getD 45 [] := by decide +kernel
theorem S0_X1_46 : S0_D1.getD 46 [] = (expandE nS0_N nS0_E1).getD 46 [] := by decide +kernel
theorem S0_X1_47 : S0_D1.getD 47 [] = (expandE nS0_N nS0_E1).getD 47 [] := by decide +kernel
theorem S0_X1_48 : S0_D1.getD 48 [] = (expandE nS0_N nS0_E1).getD 48 [] := by decide +kernel
theorem S0_X1_49 : S0_D1.getD 49 [] = (expandE nS0_N nS0_E1).getD 49 [] := by decide +kernel
theorem S0_X1_50 : S0_D1.getD 50 [] = (expandE nS0_N nS0_E1).getD 50 [] := by decide +kernel
theorem S0_X1_51 : S0_D1.getD 51 [] = (expandE nS0_N nS0_E1).getD 51 [] := by decide +kernel
theorem S0_X1_52 : S0_D1.getD 52 [] = (expandE nS0_N nS0_E1).getD 52 [] := by decide +kernel
theorem S0_X1_53 : S0_D1.getD 53 [] = (expandE nS0_N nS0_E1).getD 53 [] := by decide +kernel
theorem S0_X1_54 : S0_D1.getD 54 [] = (expandE nS0_N nS0_E1).getD 54 [] := by decide +kernel
theorem S0_X1_55 : S0_D1.getD 55 [] = (expandE nS0_N nS0_E1).getD 55 [] := by decide +kernel

theorem S0_X1 : S0_D1 = expandE nS0_N nS0_E1 :=
  NBlk.eq_of_getD_rows (S0_Dl1.trans S0_Xl1.symm) fun a ha => by
    rw [S0_Dl1] at ha
    exact match a, ha with
      | 0, _ => S0_X1_0
      | 1, _ => S0_X1_1
      | 2, _ => S0_X1_2
      | 3, _ => S0_X1_3
      | 4, _ => S0_X1_4
      | 5, _ => S0_X1_5
      | 6, _ => S0_X1_6
      | 7, _ => S0_X1_7
      | 8, _ => S0_X1_8
      | 9, _ => S0_X1_9
      | 10, _ => S0_X1_10
      | 11, _ => S0_X1_11
      | 12, _ => S0_X1_12
      | 13, _ => S0_X1_13
      | 14, _ => S0_X1_14
      | 15, _ => S0_X1_15
      | 16, _ => S0_X1_16
      | 17, _ => S0_X1_17
      | 18, _ => S0_X1_18
      | 19, _ => S0_X1_19
      | 20, _ => S0_X1_20
      | 21, _ => S0_X1_21
      | 22, _ => S0_X1_22
      | 23, _ => S0_X1_23
      | 24, _ => S0_X1_24
      | 25, _ => S0_X1_25
      | 26, _ => S0_X1_26
      | 27, _ => S0_X1_27
      | 28, _ => S0_X1_28
      | 29, _ => S0_X1_29
      | 30, _ => S0_X1_30
      | 31, _ => S0_X1_31
      | 32, _ => S0_X1_32
      | 33, _ => S0_X1_33
      | 34, _ => S0_X1_34
      | 35, _ => S0_X1_35
      | 36, _ => S0_X1_36
      | 37, _ => S0_X1_37
      | 38, _ => S0_X1_38
      | 39, _ => S0_X1_39
      | 40, _ => S0_X1_40
      | 41, _ => S0_X1_41
      | 42, _ => S0_X1_42
      | 43, _ => S0_X1_43
      | 44, _ => S0_X1_44
      | 45, _ => S0_X1_45
      | 46, _ => S0_X1_46
      | 47, _ => S0_X1_47
      | 48, _ => S0_X1_48
      | 49, _ => S0_X1_49
      | 50, _ => S0_X1_50
      | 51, _ => S0_X1_51
      | 52, _ => S0_X1_52
      | 53, _ => S0_X1_53
      | 54, _ => S0_X1_54
      | 55, _ => S0_X1_55
      | _ + 56, h => absurd h (by omega)


end N5R1
