import N5R1.Data
import N5R1.Blocks
/-! N = 5, Coulomb (s = 1): SOS block `S0` (56 × 49), part 2 of 2.  The expanded component blocks (`√3`) are `Ñ·E_c·Ñᵀ` (row by row);
the `K`-block with its corner witnesses (`KOK`; `ldl d l = P` row by row).

Generated by `lean/gen/emit_n5_s1.py` from `cert_n5_s1_short.json`
(sha256 66c5baa88a130761295e1a161f9fe35f8218c28e3defddc67ad22bcd5361e2e0).  Do not edit; regenerate. -/

namespace N5R1
open ThomsonN7 ThomsonN7.Kron ThomsonN7.Kron.Ex ThomsonN7.Cert ThomsonN7.Cert.Cert3 ThomsonN7.Cert.KB

-- large literals: elaboration budget only (no effect on what is checked)
set_option maxHeartbeats 0

theorem S0_Dl2 : S0_D2.length = 56 := by decide +kernel
theorem S0_Xl2 : (expandE nS0_N nS0_E2).length = 56 := by decide +kernel
theorem S0_X2_0 : S0_D2.getD 0 [] = (expandE nS0_N nS0_E2).getD 0 [] := by decide +kernel
theorem S0_X2_1 : S0_D2.getD 1 [] = (expandE nS0_N nS0_E2).getD 1 [] := by decide +kernel
theorem S0_X2_2 : S0_D2.getD 2 [] = (expandE nS0_N nS0_E2).getD 2 [] := by decide +kernel
theorem S0_X2_3 : S0_D2.getD 3 [] = (expandE nS0_N nS0_E2).getD 3 [] := by decide +kernel
theorem S0_X2_4 : S0_D2.getD 4 [] = (expandE nS0_N nS0_E2).getD 4 [] := by decide +kernel
theorem S0_X2_5 : S0_D2.getD 5 [] = (expandE nS0_N nS0_E2).getD 5 [] := by decide +kernel
theorem S0_X2_6 : S0_D2.getD 6 [] = (expandE nS0_N nS0_E2).getD 6 [] := by decide +kernel
theorem S0_X2_7 : S0_D2.getD 7 [] = (expandE nS0_N nS0_E2).getD 7 [] := by decide +kernel
theorem S0_X2_8 : S0_D2.getD 8 [] = (expandE nS0_N nS0_E2).getD 8 [] := by decide +kernel
theorem S0_X2_9 : S0_D2.getD 9 [] = (expandE nS0_N nS0_E2).getD 9 [] := by decide +kernel
theorem S0_X2_10 : S0_D2.getD 10 [] = (expandE nS0_N nS0_E2).getD 10 [] := by decide +kernel
theorem S0_X2_11 : S0_D2.getD 11 [] = (expandE nS0_N nS0_E2).getD 11 [] := by decide +kernel
theorem S0_X2_12 : S0_D2.getD 12 [] = (expandE nS0_N nS0_E2).getD 12 [] := by decide +kernel
theorem S0_X2_13 : S0_D2.getD 13 [] = (expandE nS0_N nS0_E2).getD 13 [] := by decide +kernel
theorem S0_X2_14 : S0_D2.getD 14 [] = (expandE nS0_N nS0_E2).getD 14 [] := by decide +kernel
theorem S0_X2_15 : S0_D2.getD 15 [] = (expandE nS0_N nS0_E2).getD 15 [] := by decide +kernel
theorem S0_X2_16 : S0_D2.getD 16 [] = (expandE nS0_N nS0_E2).getD 16 [] := by decide +kernel
theorem S0_X2_17 : S0_D2.getD 17 [] = (expandE nS0_N nS0_E2).getD 17 [] := by decide +kernel
theorem S0_X2_18 : S0_D2.getD 18 [] = (expandE nS0_N nS0_E2).getD 18 [] := by decide +kernel
theorem S0_X2_19 : S0_D2.getD 19 [] = (expandE nS0_N nS0_E2).getD 19 [] := by decide +kernel
theorem S0_X2_20 : S0_D2.getD 20 [] = (expandE nS0_N nS0_E2).getD 20 [] := by decide +kernel
theorem S0_X2_21 : S0_D2.getD 21 [] = (expandE nS0_N nS0_E2).getD 21 [] := by decide +kernel
theorem S0_X2_22 : S0_D2.getD 22 [] = (expandE nS0_N nS0_E2).getD 22 [] := by decide +kernel
theorem S0_X2_23 : S0_D2.getD 23 [] = (expandE nS0_N nS0_E2).getD 23 [] := by decide +kernel
theorem S0_X2_24 : S0_D2.getD 24 [] = (expandE nS0_N nS0_E2).getD 24 [] := by decide +kernel
theorem S0_X2_25 : S0_D2.getD 25 [] = (expandE nS0_N nS0_E2).getD 25 [] := by decide +kernel
theorem S0_X2_26 : S0_D2.getD 26 [] = (expandE nS0_N nS0_E2).getD 26 [] := by decide +kernel
theorem S0_X2_27 : S0_D2.getD 27 [] = (expandE nS0_N nS0_E2).getD 27 [] := by decide +kernel
theorem S0_X2_28 : S0_D2.getD 28 [] = (expandE nS0_N nS0_E2).getD 28 [] := by decide +kernel
theorem S0_X2_29 : S0_D2.getD 29 [] = (expandE nS0_N nS0_E2).getD 29 [] := by decide +kernel
theorem S0_X2_30 : S0_D2.getD 30 [] = (expandE nS0_N nS0_E2).getD 30 [] := by decide +kernel
theorem S0_X2_31 : S0_D2.getD 31 [] = (expandE nS0_N nS0_E2).getD 31 [] := by decide +kernel
theorem S0_X2_32 : S0_D2.getD 32 [] = (expandE nS0_N nS0_E2).getD 32 [] := by decide +kernel
theorem S0_X2_33 : S0_D2.getD 33 [] = (expandE nS0_N nS0_E2).getD 33 [] := by decide +kernel
theorem S0_X2_34 : S0_D2.getD 34 [] = (expandE nS0_N nS0_E2).getD 34 [] := by decide +kernel
theorem S0_X2_35 : S0_D2.getD 35 [] = (expandE nS0_N nS0_E2).getD 35 [] := by decide +kernel
theorem S0_X2_36 : S0_D2.getD 36 [] = (expandE nS0_N nS0_E2).getD 36 [] := by decide +kernel
theorem S0_X2_37 : S0_D2.getD 37 [] = (expandE nS0_N nS0_E2).getD 37 [] := by decide +kernel
theorem S0_X2_38 : S0_D2.getD 38 [] = (expandE nS0_N nS0_E2).getD 38 [] := by decide +kernel
theorem S0_X2_39 : S0_D2.getD 39 [] = (expandE nS0_N nS0_E2).getD 39 [] := by decide +kernel
theorem S0_X2_40 : S0_D2.getD 40 [] = (expandE nS0_N nS0_E2).getD 40 [] := by decide +kernel
theorem S0_X2_41 : S0_D2.getD 41 [] = (expandE nS0_N nS0_E2).getD 41 [] := by decide +kernel
theorem S0_X2_42 : S0_D2.getD 42 [] = (expandE nS0_N nS0_E2).getD 42 [] := by decide +kernel
theorem S0_X2_43 : S0_D2.getD 43 [] = (expandE nS0_N nS0_E2).getD 43 [] := by decide +kernel
theorem S0_X2_44 : S0_D2.getD 44 [] = (expandE nS0_N nS0_E2).getD 44 [] := by decide +kernel
theorem S0_X2_45 : S0_D2.getD 45 [] = (expandE nS0_N nS0_E2).getD 45 [] := by decide +kernel
theorem S0_X2_46 : S0_D2.getD 46 [] = (expandE nS0_N nS0_E2).getD 46 [] := by decide +kernel
theorem S0_X2_47 : S0_D2.getD 47 [] = (expandE nS0_N nS0_E2).getD 47 [] := by decide +kernel
theorem S0_X2_48 : S0_D2.getD 48 [] = (expandE nS0_N nS0_E2).getD 48 [] := by decide +kernel
theorem S0_X2_49 : S0_D2.getD 49 [] = (expandE nS0_N nS0_E2).getD 49 [] := by decide +kernel
theorem S0_X2_50 : S0_D2.getD 50 [] = (expandE nS0_N nS0_E2).getD 50 [] := by decide +kernel
theorem S0_X2_51 : S0_D2.getD 51 [] = (expandE nS0_N nS0_E2).getD 51 [] := by decide +kernel
theorem S0_X2_52 : S0_D2.getD 52 [] = (expandE nS0_N nS0_E2).getD 52 [] := by decide +kernel
theorem S0_X2_53 : S0_D2.getD 53 [] = (expandE nS0_N nS0_E2).getD 53 [] := by decide +kernel
theorem S0_X2_54 : S0_D2.getD 54 [] = (expandE nS0_N nS0_E2).getD 54 [] := by decide +kernel
theorem S0_X2_55 : S0_D2.getD 55 [] = (expandE nS0_N nS0_E2).getD 55 [] := by decide +kernel

theorem S0_X2 : S0_D2 = expandE nS0_N nS0_E2 :=
  NBlk.eq_of_getD_rows (S0_Dl2.trans S0_Xl2.symm) fun a ha => by
    rw [S0_Dl2] at ha
    exact match a, ha with
      | 0, _ => S0_X2_0
      | 1, _ => S0_X2_1
      | 2, _ => S0_X2_2
      | 3, _ => S0_X2_3
      | 4, _ => S0_X2_4
      | 5, _ => S0_X2_5
      | 6, _ => S0_X2_6
      | 7, _ => S0_X2_7
      | 8, _ => S0_X2_8
      | 9, _ => S0_X2_9
      | 10, _ => S0_X2_10
      | 11, _ => S0_X2_11
      | 12, _ => S0_X2_12
      | 13, _ => S0_X2_13
      | 14, _ => S0_X2_14
      | 15, _ => S0_X2_15
      | 16, _ => S0_X2_16
      | 17, _ => S0_X2_17
      | 18, _ => S0_X2_18
      | 19, _ => S0_X2_19
      | 20, _ => S0_X2_20
      | 21, _ => S0_X2_21
      | 22, _ => S0_X2_22
      | 23, _ => S0_X2_23
      | 24, _ => S0_X2_24
      | 25, _ => S0_X2_25
      | 26, _ => S0_X2_26
      | 27, _ => S0_X2_27
      | 28, _ => S0_X2_28
      | 29, _ => S0_X2_29
      | 30, _ => S0_X2_30
      | 31, _ => S0_X2_31
      | 32, _ => S0_X2_32
      | 33, _ => S0_X2_33
      | 34, _ => S0_X2_34
      | 35, _ => S0_X2_35
      | 36, _ => S0_X2_36
      | 37, _ => S0_X2_37
      | 38, _ => S0_X2_38
      | 39, _ => S0_X2_39
      | 40, _ => S0_X2_40
      | 41, _ => S0_X2_41
      | 42, _ => S0_X2_42
      | 43, _ => S0_X2_43
      | 44, _ => S0_X2_44
      | 45, _ => S0_X2_45
      | 46, _ => S0_X2_46
      | 47, _ => S0_X2_47
      | 48, _ => S0_X2_48
      | 49, _ => S0_X2_49
      | 50, _ => S0_X2_50
      | 51, _ => S0_X2_51
      | 52, _ => S0_X2_52
      | 53, _ => S0_X2_53
      | 54, _ => S0_X2_54
      | 55, _ => S0_X2_55
      | _ + 56, h => absurd h (by omega)

theorem nS0_Pl : (NBlk.ldl nS0_d nS0_l).length = 49 := by decide +kernel
theorem nS0_Pr : nS0_P.length = 49 := by decide +kernel
theorem nS0_P0 : (NBlk.ldl nS0_d nS0_l).getD 0 [] = nS0_P.getD 0 [] := by decide +kernel
theorem nS0_P1 : (NBlk.ldl nS0_d nS0_l).getD 1 [] = nS0_P.getD 1 [] := by decide +kernel
theorem nS0_P2 : (NBlk.ldl nS0_d nS0_l).getD 2 [] = nS0_P.getD 2 [] := by decide +kernel
theorem nS0_P3 : (NBlk.ldl nS0_d nS0_l).getD 3 [] = nS0_P.getD 3 [] := by decide +kernel
theorem nS0_P4 : (NBlk.ldl nS0_d nS0_l).getD 4 [] = nS0_P.getD 4 [] := by decide +kernel
theorem nS0_P5 : (NBlk.ldl nS0_d nS0_l).getD 5 [] = nS0_P.getD 5 [] := by decide +kernel
theorem nS0_P6 : (NBlk.ldl nS0_d nS0_l).getD 6 [] = nS0_P.getD 6 [] := by decide +kernel
theorem nS0_P7 : (NBlk.ldl nS0_d nS0_l).getD 7 [] = nS0_P.getD 7 [] := by decide +kernel
theorem nS0_P8 : (NBlk.ldl nS0_d nS0_l).getD 8 [] = nS0_P.getD 8 [] := by decide +kernel
theorem nS0_P9 : (NBlk.ldl nS0_d nS0_l).getD 9 [] = nS0_P.getD 9 [] := by decide +kernel
theorem nS0_P10 : (NBlk.ldl nS0_d nS0_l).getD 10 [] = nS0_P.getD 10 [] := by decide +kernel
theorem nS0_P11 : (NBlk.ldl nS0_d nS0_l).getD 11 [] = nS0_P.getD 11 [] := by decide +kernel
theorem nS0_P12 : (NBlk.ldl nS0_d nS0_l).getD 12 [] = nS0_P.getD 12 [] := by decide +kernel
theorem nS0_P13 : (NBlk.ldl nS0_d nS0_l).getD 13 [] = nS0_P.getD 13 [] := by decide +kernel
theorem nS0_P14 : (NBlk.ldl nS0_d nS0_l).getD 14 [] = nS0_P.getD 14 [] := by decide +kernel
theorem nS0_P15 : (NBlk.ldl nS0_d nS0_l).getD 15 [] = nS0_P.getD 15 [] := by decide +kernel
theorem nS0_P16 : (NBlk.ldl nS0_d nS0_l).getD 16 [] = nS0_P.getD 16 [] := by decide +kernel
theorem nS0_P17 : (NBlk.ldl nS0_d nS0_l).getD 17 [] = nS0_P.getD 17 [] := by decide +kernel
theorem nS0_P18 : (NBlk.ldl nS0_d nS0_l).getD 18 [] = nS0_P.getD 18 [] := by decide +kernel
theorem nS0_P19 : (NBlk.ldl nS0_d nS0_l).getD 19 [] = nS0_P.getD 19 [] := by decide +kernel
theorem nS0_P20 : (NBlk.ldl nS0_d nS0_l).getD 20 [] = nS0_P.getD 20 [] := by decide +kernel
theorem nS0_P21 : (NBlk.ldl nS0_d nS0_l).getD 21 [] = nS0_P.getD 21 [] := by decide +kernel
theorem nS0_P22 : (NBlk.ldl nS0_d nS0_l).getD 22 [] = nS0_P.getD 22 [] := by decide +kernel
theorem nS0_P23 : (NBlk.ldl nS0_d nS0_l).getD 23 [] = nS0_P.getD 23 [] := by decide +kernel
theorem nS0_P24 : (NBlk.ldl nS0_d nS0_l).getD 24 [] = nS0_P.getD 24 [] := by decide +kernel
theorem nS0_P25 : (NBlk.ldl nS0_d nS0_l).getD 25 [] = nS0_P.getD 25 [] := by decide +kernel
theorem nS0_P26 : (NBlk.ldl nS0_d nS0_l).getD 26 [] = nS0_P.getD 26 [] := by decide +kernel
theorem nS0_P27 : (NBlk.ldl nS0_d nS0_l).getD 27 [] = nS0_P.getD 27 [] := by decide +kernel
theorem nS0_P28 : (NBlk.ldl nS0_d nS0_l).getD 28 [] = nS0_P.getD 28 [] := by decide +kernel
theorem nS0_P29 : (NBlk.ldl nS0_d nS0_l).getD 29 [] = nS0_P.getD 29 [] := by decide +kernel
theorem nS0_P30 : (NBlk.ldl nS0_d nS0_l).getD 30 [] = nS0_P.getD 30 [] := by decide +kernel
theorem nS0_P31 : (NBlk.ldl nS0_d nS0_l).getD 31 [] = nS0_P.getD 31 [] := by decide +kernel
theorem nS0_P32 : (NBlk.ldl nS0_d nS0_l).getD 32 [] = nS0_P.getD 32 [] := by decide +kernel
theorem nS0_P33 : (NBlk.ldl nS0_d nS0_l).getD 33 [] = nS0_P.getD 33 [] := by decide +kernel
theorem nS0_P34 : (NBlk.ldl nS0_d nS0_l).getD 34 [] = nS0_P.getD 34 [] := by decide +kernel
theorem nS0_P35 : (NBlk.ldl nS0_d nS0_l).getD 35 [] = nS0_P.getD 35 [] := by decide +kernel
theorem nS0_P36 : (NBlk.ldl nS0_d nS0_l).getD 36 [] = nS0_P.getD 36 [] := by decide +kernel
theorem nS0_P37 : (NBlk.ldl nS0_d nS0_l).getD 37 [] = nS0_P.getD 37 [] := by decide +kernel
theorem nS0_P38 : (NBlk.ldl nS0_d nS0_l).getD 38 [] = nS0_P.getD 38 [] := by decide +kernel
theorem nS0_P39 : (NBlk.ldl nS0_d nS0_l).getD 39 [] = nS0_P.getD 39 [] := by decide +kernel
theorem nS0_P40 : (NBlk.ldl nS0_d nS0_l).getD 40 [] = nS0_P.getD 40 [] := by decide +kernel
theorem nS0_P41 : (NBlk.ldl nS0_d nS0_l).getD 41 [] = nS0_P.getD 41 [] := by decide +kernel
theorem nS0_P42 : (NBlk.ldl nS0_d nS0_l).getD 42 [] = nS0_P.getD 42 [] := by decide +kernel
theorem nS0_P43 : (NBlk.ldl nS0_d nS0_l).getD 43 [] = nS0_P.getD 43 [] := by decide +kernel
theorem nS0_P44 : (NBlk.ldl nS0_d nS0_l).getD 44 [] = nS0_P.getD 44 [] := by decide +kernel
theorem nS0_P45 : (NBlk.ldl nS0_d nS0_l).getD 45 [] = nS0_P.getD 45 [] := by decide +kernel
theorem nS0_P46 : (NBlk.ldl nS0_d nS0_l).getD 46 [] = nS0_P.getD 46 [] := by decide +kernel
theorem nS0_P47 : (NBlk.ldl nS0_d nS0_l).getD 47 [] = nS0_P.getD 47 [] := by decide +kernel
theorem nS0_P48 : (NBlk.ldl nS0_d nS0_l).getD 48 [] = nS0_P.getD 48 [] := by decide +kernel

theorem nS0_hP : NBlk.ldl nS0_d nS0_l = nS0_P :=
  NBlk.eq_of_getD_rows (nS0_Pl.trans nS0_Pr.symm) fun a ha => by
    rw [nS0_Pl] at ha
    exact match a, ha with
      | 0, _ => nS0_P0
      | 1, _ => nS0_P1
      | 2, _ => nS0_P2
      | 3, _ => nS0_P3
      | 4, _ => nS0_P4
      | 5, _ => nS0_P5
      | 6, _ => nS0_P6
      | 7, _ => nS0_P7
      | 8, _ => nS0_P8
      | 9, _ => nS0_P9
      | 10, _ => nS0_P10
      | 11, _ => nS0_P11
      | 12, _ => nS0_P12
      | 13, _ => nS0_P13
      | 14, _ => nS0_P14
      | 15, _ => nS0_P15
      | 16, _ => nS0_P16
      | 17, _ => nS0_P17
      | 18, _ => nS0_P18
      | 19, _ => nS0_P19
      | 20, _ => nS0_P20
      | 21, _ => nS0_P21
      | 22, _ => nS0_P22
      | 23, _ => nS0_P23
      | 24, _ => nS0_P24
      | 25, _ => nS0_P25
      | 26, _ => nS0_P26
      | 27, _ => nS0_P27
      | 28, _ => nS0_P28
      | 29, _ => nS0_P29
      | 30, _ => nS0_P30
      | 31, _ => nS0_P31
      | 32, _ => nS0_P32
      | 33, _ => nS0_P33
      | 34, _ => nS0_P34
      | 35, _ => nS0_P35
      | 36, _ => nS0_P36
      | 37, _ => nS0_P37
      | 38, _ => nS0_P38
      | 39, _ => nS0_P39
      | 40, _ => nS0_P40
      | 41, _ => nS0_P41
      | 42, _ => nS0_P42
      | 43, _ => nS0_P43
      | 44, _ => nS0_P44
      | 45, _ => nS0_P45
      | 46, _ => nS0_P46
      | 47, _ => nS0_P47
      | 48, _ => nS0_P48
      | _ + 49, h => absurd h (by omega)

theorem nS0_ok0 : okF 49 nS0_C0 = true := by decide +kernel
theorem nS0_lin0 : NBlk.matAdd nS0_P nS0_R0 = lin κ0 nS0_Es := by decide +kernel
theorem nS0_corner0 : CornerOK 3 49 nS0_Es κ0 nS0_C0 :=
  ⟨by decide +kernel, nS0_ok0, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nS0_C0 = NBlk.matAdd (NBlk.ldl nS0_d nS0_l) nS0_R0 from rfl, nS0_hP]
    exact nS0_lin0⟩
theorem nS0_ok1 : okF 49 nS0_C1 = true := by decide +kernel
theorem nS0_lin1 : NBlk.matAdd nS0_P nS0_R1 = lin κ1 nS0_Es := by decide +kernel
theorem nS0_corner1 : CornerOK 3 49 nS0_Es κ1 nS0_C1 :=
  ⟨by decide +kernel, nS0_ok1, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nS0_C1 = NBlk.matAdd (NBlk.ldl nS0_d nS0_l) nS0_R1 from rfl, nS0_hP]
    exact nS0_lin1⟩
theorem nS0_ok2 : okF 49 nS0_C2 = true := by decide +kernel
theorem nS0_lin2 : NBlk.matAdd nS0_P nS0_R2 = lin κ2 nS0_Es := by decide +kernel
theorem nS0_corner2 : CornerOK 3 49 nS0_Es κ2 nS0_C2 :=
  ⟨by decide +kernel, nS0_ok2, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nS0_C2 = NBlk.matAdd (NBlk.ldl nS0_d nS0_l) nS0_R2 from rfl, nS0_hP]
    exact nS0_lin2⟩
theorem nS0_ok3 : okF 49 nS0_C3 = true := by decide +kernel
theorem nS0_lin3 : NBlk.matAdd nS0_P nS0_R3 = lin κ3 nS0_Es := by decide +kernel
theorem nS0_corner3 : CornerOK 3 49 nS0_Es κ3 nS0_C3 :=
  ⟨by decide +kernel, nS0_ok3, by decide +kernel, by decide +kernel, by
    rw [show NBlk.entMat nS0_C3 = NBlk.matAdd (NBlk.ldl nS0_d nS0_l) nS0_R3 from rfl, nS0_hP]
    exact nS0_lin3⟩
/-- The checked `K`-block `S0`. -/
theorem nS0_kok : KOK 3 49 κs nS0_N nS0_Es [nS0_C0, nS0_C1, nS0_C2, nS0_C3] :=
  ⟨by decide +kernel, by decide +kernel, by decide +kernel,
    .cons nS0_corner0 (.cons nS0_corner1 (.cons nS0_corner2 (.cons nS0_corner3 .nil)))⟩
theorem nS0_mN : 56 ≤ nS0_N.length := by decide +kernel

end N5R1
