import Mathlib

/-!
# N = 5, Riesz s = 2: the one-dimensional minorant `H ≤ φ₂` on `[-1, 1)`

`Hpoly` is the degree-10 polynomial `H` of the three-point certificate (`cert_n5_s2_short.json`, monomial form). With
`φ₂(t) = 1/(2-2t)`:
* `1 - (2-2t) H(t) = (t+1)(2t+1)² t² q(t)` (`factor`);
* `q(t) - 1/100 = Σ (bᵢ - 1/100) C(6,i) ((1+t)/2)ⁱ ((1-t)/2)⁶⁻ⁱ` with all `bᵢ - 1/100 ≥ 0` (Bernstein form, `q_bern`), so
  `q > 0` on `[-1, 1]` (`q_pos`).

Hence `H ≤ φ₂` on `[-1, 1)`, with equality exactly at `t ∈ {-1, -1/2, 0}` (`H_le`, `H_eq_iff`).
Generated by `lean/gen/gen_minor.py`.  Regenerate; do not edit.
-/

namespace N5R2

/-- The polynomial `H` of the certificate. -/
noncomputable def Hpoly (t : ℝ) : ℝ :=
  ((1 : ℝ) / 2) * t ^ 0 + ((1 : ℝ) / 2) * t ^ 1 + ((10279028337839033858341133629 : ℝ) / 25705722895745954321793024000) * t ^ 2 + ((-1084244369104437683349886391 : ℝ) / 171371485971639695478620160000) * t ^ 3 + ((-150749397997864698924804973603 : ℝ) / 514114457914919086435860480000) * t ^ 4 + ((13467492503835436663199671991 : ℝ) / 85685742985819847739310080000) * t ^ 5 + ((43210707187387183998680214971 : ℝ) / 128528614478729771608965120000) * t ^ 6 + ((-2916104247463196871929724113 : ℝ) / 21421435746454961934827520000) * t ^ 7 + ((600681775 : ℝ) / 8589934592) * t ^ 8 + ((1834674173541375428092543 : ℝ) / 3347099335383587802316800) * t ^ 9 + ((322207483 : ℝ) / 1073741824) * t ^ 10

/-- The cofactor `q` with `1 - (2-2t) H = (t+1)(2t+1)² t² q`. -/
noncomputable def qpoly (t : ℝ) : ℝ :=
  ((2573833110033943302555378371 : ℝ) / 12852861447872977160896512000) * t ^ 0 + ((-1798148560714827408839463161 : ℝ) / 9520638109535538637701120000) * t ^ 1 + ((-4313315403675568468155539639 : ℝ) / 51411445791491908643586048000) * t ^ 2 + ((9795328730449858150796543087 : ℝ) / 42842871492909923869655040000) * t ^ 3 + ((-166363497706664597730343 : ℝ) / 2231399556922391868211200) * t ^ 4 + ((-1178509521363998767224257 : ℝ) / 6694198670767175604633600) * t ^ 5 + ((322207483 : ℝ) / 2147483648) * t ^ 6

theorem factor (t : ℝ) : 1 - (2 - 2 * t) * Hpoly t = (t + 1) * (2 * t + 1) ^ 2 * t ^ 2 * qpoly t := by
  unfold Hpoly qpoly; ring

theorem q_bern (t : ℝ) : qpoly t - 1 / 100 =
    ((20191603365107703732090817 : ℝ) / 63470920730236924251340800) * 1 * ((1 + t) / 2) ^ 0 * ((1 - t) / 2) ^ 6 + ((35201004804221936828885563559 : ℝ) / 771171686872378629653790720000) * 6 * ((1 + t) / 2) ^ 1 * ((1 - t) / 2) ^ 5 + ((499548517747267104749696358349 : ℝ) / 963964608590473287067238400000) * 15 * ((1 + t) / 2) ^ 2 * ((1 - t) / 2) ^ 4 + ((3605879677609832351773887313 : ℝ) / 85685742985819847739310080000) * 20 * ((1 + t) / 2) ^ 3 * ((1 - t) / 2) ^ 3 + ((353757234548047299284670070397 : ℝ) / 1927929217180946574134476800000) * 15 * ((1 + t) / 2) ^ 4 * ((1 - t) / 2) ^ 2 + ((22020022728530787319869417371 : ℝ) / 771171686872378629653790720000) * 6 * ((1 + t) / 2) ^ 5 * ((1 - t) / 2) ^ 1 + ((41 : ℝ) / 900) * 1 * ((1 + t) / 2) ^ 6 * ((1 - t) / 2) ^ 0 := by
  unfold qpoly; ring

theorem q_pos {t : ℝ} (h1 : -1 ≤ t) (h2 : t ≤ 1) : 0 < qpoly t := by
  have ha : 0 ≤ (1 + t) / 2 := by linarith
  have hc : 0 ≤ (1 - t) / 2 := by linarith
  have hb := q_bern t
  have : 0 ≤ qpoly t - 1 / 100 := by rw [hb]; positivity
  linarith

/-- **`H ≤ φ₂` on `[-1, 1)`.** -/
theorem H_le {t : ℝ} (h1 : -1 ≤ t) (h2 : t < 1) : Hpoly t ≤ 1 / (2 - 2 * t) := by
  have hd : 0 < 2 - 2 * t := by linarith
  rw [le_div_iff₀ hd]
  have hf := factor t
  have hq := q_pos h1 h2.le
  have : 0 ≤ (t + 1) * (2 * t + 1) ^ 2 * t ^ 2 * qpoly t := by
    have : 0 ≤ t + 1 := by linarith
    positivity
  nlinarith

/-- Equality holds exactly at the inner products of the triangular bipyramid. -/
theorem H_eq_iff {t : ℝ} (h1 : -1 ≤ t) (h2 : t < 1) :
    Hpoly t = 1 / (2 - 2 * t) ↔ t = -1 ∨ t = -1 / 2 ∨ t = 0 := by
  have hd : 0 < 2 - 2 * t := by linarith
  have hq := q_pos h1 h2.le
  have hf := factor t
  constructor
  · intro h
    have h0 : (t + 1) * (2 * t + 1) ^ 2 * t ^ 2 * qpoly t = 0 := by
      rw [← hf, h, mul_one_div_cancel hd.ne', sub_self]
    have hqne : qpoly t ≠ 0 := hq.ne'
    rcases mul_eq_zero.1 h0 with h0 | h0
    · rcases mul_eq_zero.1 h0 with h0 | h0
      · rcases mul_eq_zero.1 h0 with h0 | h0
        · left; linarith
        · right; left; have := pow_eq_zero_iff (n := 2) (by norm_num) |>.1 h0; linarith
      · right; right; exact pow_eq_zero_iff (n := 2) (by norm_num) |>.1 h0
    · exact absurd h0 hqne
  · intro h
    have h0 : (t + 1) * (2 * t + 1) ^ 2 * t ^ 2 * qpoly t = 0 := by
      rcases h with h | h | h <;> subst h <;> ring
    rw [← hf] at h0
    rw [eq_div_iff hd.ne']
    linarith

end N5R2
